### ISSUE TITLE
methods inherited via more than one class are documented more than once

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#10]
See for example http://twistedmatrix.com/documents/9.0.0/api/twisted.internet.interfaces.IReadWriteDescriptor.html

I have this vague memory that there is code that's supposed to suppress the repeated documentation, but it clearly isn't working.

---

Imported from Launchpad using lp2gh.
- date created: 2010-02-21T22:57:04Z
- owner: mwhudson
- the launchpad url was https://bugs.launchpad.net/bugs/525521

**Comment by mthuurne** [comment]
Assuming this is the problem, it still occurs with the latest pydoctor:

> Inherited from IFileDescriptor (via IReadDescriptor):
> ...
> Inherited from IFileDescriptor (via IWriteDescriptor):

So `IFileDescriptor` is listed as a superclass twice as a result of a diamond-shaped inheritance. However, `ILoggingContext` is listed only once, despite it being reachable via the same two routes:

> Inherited from ILoggingContext (via IReadDescriptor, IFileDescriptor):

**Comment by tristanlatr** [comment]
We should probably adapt our own version of the C3 algorithm that works with `model.Class` objects. 

A nice implementation can be found at https://github.com/pilosus/c3linear
