### ISSUE TITLE
Detect and use docstrings set after-the-fact.

### ISSUE THREAD

**Issue by tomprince** [twisted/pydoctor#102]
Twisted has some code that does something like

``` python
if _PY3:
   def func(args):
       pass
else:
    def func(args):
        pass

func.__doc__ = """
func does some stuff.
```

to avoid duplicating a docstring. Unfortunately, pydoctor doesn't pick this up, so it appears that `func` is undocumented.

**Comment by twm** [comment]
This looks similar to https://twistedmatrix.com/trac/ticket/9745 Twisted's `twisted.python.deprecate` module provides a `@deprecated` decorator that appends a deprecation notice to the docstring. pydoctor doesn't seem to notice this.
