### ISSUE TITLE
Sphinx inventory file is created in text mode - should be binary

### ISSUE THREAD

**Issue by gerph** [twisted/pydoctor#103]
https://github.com/twisted/pydoctor/blob/master/pydoctor/sphinx.py#L39

```
    def _openFileForWriting(self, path):
        """
        Helper for testing.
        """
        return open(path, 'w')
```

The data being written to the file is binary, (it's zlibcompressed data) so opening in 'w' mode will corrupt the data on Windows-thefile needs to be opened in binary mode. ie `open(path, 'wb')`

**Comment by mthuurne** [comment]
This was stealth-fixed by @GaretJax in  #152.
