### ISSUE TITLE
Show aliases for functions and methods

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#12]
If a function or method is assigned alternate names ("func2 = func1"), pydoctor should list those aliases in the function or method documentation.

---

Imported from Launchpad using lp2gh.
- date created: 2011-01-12T21:08:25Z
- owner: gxti
- the launchpad url was https://bugs.launchpad.net/bugs/702127

**Comment by mwhudson** [comment]
(by mwhudson)
Yup, sounds sane and probably not too terribly hard.

**Comment by tristanlatr** [comment]
Closing this issue as it's the same as #313
