### ISSUE TITLE
Rephrase Python 3 tox instructions in README.rst

### ISSUE THREAD

**Issue by peterjc** [twisted/pydoctor#122]
Unnatural phrasing in the `README.rst`:

> Since Python 3 is not yet supported, you the case in which your default tox runs with Python 3, call the tox as:
> 
> python2 -m tox -e pyflakes

Suggestion:

> Python 3 is not yet supported, so if by default your tox installation uses Python 3, you should call tox using:
> 
> python2 -m tox -e pyflakes

**Comment by mthuurne** [comment]
I removed the text in question when revising the README prior to the 20.7.0 release. We do support Python 3 now.
