### ISSUE TITLE
Support google/numpy docstrings, too

### ISSUE THREAD

**Issue by matejak** [twisted/pydoctor#123]
Currently, `pydoctor` seems to support only javadoc-style docstrings, however, there seems to be a trend towards Google or numpy-style docstrings (supported e.g. by the [napoleon Sphinx extension](https://pypi.python.org/pypi/sphinxcontrib-napoleon). It would be cool if `pydoctor` could accept those as well.

**Comment by tristanlatr** [comment]
This software can automatically convert google/numpy docstrings to reST or javadoc style 
https://github.com/dadadel/pyment

**Comment by tristanlatr** [comment]
A better option: integrate a slightly modifier version of napoleon GoogleDocstring and NumpyDocstring (Or even just use sphinx napoleon extension as a library) and apply a pre-processing to all docstrings. 

https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/ext/napoleon/docstring.py
