### ISSUE TITLE
"invalid ref" to symbol that is present in module namespace

### ISSUE THREAD

**Issue by wsanchez** [twisted/pydoctor#128]
In this build: https://buildbot.twistedmatrix.com/builders/documentation/builds/1752

There are numerous errors noted by pydoctor of this form:

{{{
twisted.application.runner._exit.ExitStatus.EX_CANTCREAT: invalid ref to 'ValueConstant' resolved as 'constantly.ValueConstant'
}}}

I find this confusing, as `ValueConstant` is a symbol defined in the module namespace, so I'm unsure why it's being called an "invalid ref" here.

**Comment by mthuurne** [comment]
This message is logged when a short identifier is successfully resolved to a full name, but the full name isn't found in any Sphinx inventory. So the most likely cause is that pydoctor was run without a Sphinx inventory covering Constantly.

I agree that the message is confusing though. The problem isn't that the reference is invalid, but that it could not be found in the project itself or any of the given inventories.
