### ISSUE TITLE
allow for local intersphinx caching

### ISSUE THREAD

**Issue by glyph** [twisted/pydoctor#129]
Right now the only way I can see that pydoctor allows for intersphinx inventories to be used is to fetch them every time.

There should be a way to cache these so they can be checked into a project repo and not fetched every time, to allow for running tests like Twisted's, which check that documentation generation doesn't fail, offline.

**Comment by mwhudson** [comment]
Yeah, I think @adiroiban and I talked about this when I reviewed the initial intersphinx work and it should just be done.

**Comment by adiroiban** [comment]
There is also this ticket https://github.com/twisted/pydoctor/issues/120

**Comment by twm** [comment]
#143 seems to have resolved this.
