### ISSUE TITLE
introspection for C modules

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#14]
affects pydoctor

It would be really nice if pydoctor could support introspection next to
parsing of Python code. I work with a lot of projects that have Python
code that is partially in C and partially in Python itself, and this is
## the only thing blocking us from adopting pydoctor atm.

Jelmer Vernooij <email address hidden> - http://samba.org/~jelmer/
Jabber: <email address hidden>

---

Imported from Launchpad using lp2gh.
- date created: 2009-01-28T02:30:43Z
- owner: jelmer
- the launchpad url was https://bugs.launchpad.net/bugs/322159

**Comment by mwhudson** [comment]
(by mwhudson)
I can't really ever imagine working on this myself, sad to say.

**Comment by mwhudson** [comment]
(by jelmer)
I'd be interested in having a look at this - subvertpy and samba both need it -, would you be able to discuss this some time ?

**Comment by mwhudson** [comment]
(by jelmer)
discuss as-in a pre-implementation call of some sort, I'm a bit clueless as to where to start and what the best way is to add this kind of support into pydoctor.

**Comment by mwhudson** [comment]
(by mwhudson)
On Mon, 29 Nov 2010 10:13:17 -0000, Jelmer Vernooij <email address hidden> wrote:
> discuss as-in a pre-implementation call of some sort, I'm a bit clueless
> as to where to start and what the best way is to add this kind of
> support into pydoctor.

Well, basically, for a C module I guess you want to insert a
pydoctor.model.Module object that describes the module you're
introspecting... here's a start, perhaps?

    lp:~mwhudson/pydoctor/introspect-c-modules

See if that makes any sense :-)  You need to run like this:

 .../introspect-c-modules/bin/pydoctor \
 ~/canonical/repos/subvertpy/trunk/subvertpy --introspect \
 subvertpy.client --introspect subvertpy.repos --introspect subvertpy.wc \
 --html-output subvertpy-doc

from somewhere you can import subvertpy.client etc from.  The output
looks like this:

    http://people.canonical.com/~mwh/subvertpy-doc/subvertpy.repos.Repository.html

Hope this helps!  I think it's quite good for a 20 minute hack :-)

Cheers,
mwh

**Comment by mwhudson** [comment]
(by jelmer)
On Wed, 2010-12-01 at 03:07 +0000, Michael Hudson-Doyle wrote:
> On Mon, 29 Nov 2010 10:13:17 -0000, Jelmer Vernooij <email address hidden> wrote:
> > discuss as-in a pre-implementation call of some sort, I'm a bit clueless
> > as to where to start and what the best way is to add this kind of
> > support into pydoctor.
> Well, basically, for a C module I guess you want to insert a
> pydoctor.model.Module object that describes the module you're
> introspecting... here's a start, perhaps?
> 
>     lp:~mwhudson/pydoctor/introspect-c-modules
> 
> See if that makes any sense :-)  You need to run like this:
> 
>  .../introspect-c-modules/bin/pydoctor \
>  ~/canonical/repos/subvertpy/trunk/subvertpy --introspect \
>  subvertpy.client --introspect subvertpy.repos --introspect subvertpy.wc \
>  --html-output subvertpy-doc
> 
> from somewhere you can import subvertpy.client etc from.  The output
> looks like this:
> 
>     http://people.canonical.com/~mwh/subvertpy-
> doc/subvertpy.repos.Repository.html
> 
> Hope this helps!  I think it's quite good for a 20 minute hack :-)
Uhm, wow! :-) This is much more than I was hoping for, thanks! 

It does indeed work well on subvertpy. I'll try it on Samba tonight.

Cheers,

Jelmer

**Comment by mwhudson** [comment]
(by jelmer)
Attached a branch; pydoctor now automatically introspects .so or dll files (using imp.get_suffixes()). I also fixed a minor bug since linenumber isn't known for introspected modules.

**Comment by mwhudson** [comment]
(by jelmer)
This now works well with Samba and its almost 3 dozen C extensions:

http://samba.org/~jelmer/samba4/pydoctor/

**Comment by mwhudson** [comment]
(by mwhudson)
Hi, I grabbed your branch, made a few more changes and merged it to trunk :-)

Thanks for the prod and the code!

**Comment by mthuurne** [comment]
@jelmer Is the current introspection sufficient or is more functionality needed?

Note that there is currently no unit test coverage for the introspection code, so it does run the risk of getting broken as pydoctor is being modernized.

**Comment by jelmer** [comment]
The current introspection works well enough for me; there are almost certainly things that could be improved, though. I don't have a good idea of what they are at the moment, but can file issues about those as I find them.

Tests would certainly be nice. :-)

**Comment by mthuurne** [comment]
There is some minimal unit test coverage for introspection now.

I'm closing this issue. If anything is broken or insufficient, that can be tracked in a new and more specific issue, such as #208.
