### ISSUE TITLE
Drop epydoc support

### ISSUE THREAD

**Issue by jelmer** [twisted/pydoctor#147]
Please consider moving away from the use of Epydoc in pydoctor.  Epydoc is basically unmaintained upstream.  Also, it is only supported for Python 2, so it will reach its end of life along with Python 2 sometime in 2020.

**Comment by glyph** [comment]
Probably the best way forward here is to vendor in epydoc and start porting it to py3.

**Comment by mwhudson** [comment]
We probably only use a fairly small part for epydoc.

**Comment by mthuurne** [comment]
Please have a look at #155, it imports those parts of epydoc that pydoctor uses into the pydoctor source tree.

**Comment by hawkowl** [comment]
This is done. Thank you @mthuurne !

**Comment by glyph** [comment]
Presumably “this” not being dropping epytext support? :)

**Comment by hawkowl** [comment]
yes :)
