### ISSUE TITLE
Indexes list private class and modules

### ISSUE THREAD

**Issue by brvier** [twisted/pydoctor#153]
Indexes list private class and modules.

Adding an option for hiding them ?

**Comment by mthuurne** [comment]
Perhaps pydoctor should even hide private classes and modules under the "Show Private API" link by default?

**Comment by mthuurne** [comment]
There is an inconsistency regarding private modules at the moment: in the top-level index, they are listed, while in package doc pages they are hidden without the "Show Private API" link appearing.
