### ISSUE TITLE
pydoctor should have the equivalent of __docformat__ = "restructuredtext en"

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#16]
Originally reported as Twisted issue 2187:

> epydoc has a epytext variant that's valid restructured text. You can either set **docformat** = "restructuredtext en" in your module, or pass --docformat restructuredtext to epydoc to use it.
> 
> pydoctor should support these as well, so that it can be a better drop-in replacement for epydoc. For instance, bzr's source uses restructuredtext format epytext, so pydoctor isn't hugely useful with it.

---

Imported from Launchpad using lp2gh.
- date created: 2009-08-06T18:47:24Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/410000

**Comment by mwhudson** [comment]
(by mwhudson)
pydoctor has supported --docformat for ages now.  It doesn't support __docformat__ in modules, but I don't know how much I care.

**Comment by tristanlatr** [comment]
This feature could to be actually useful for our own documentation !
