### ISSUE TITLE
Use "enum.Enum" for enumerations

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#162]
There are several enum-like constructs in pydoctor at the moment. For example in `pydoctor.model` we have:

```py
class DocLocation:
    OWN_PAGE = 1
    PARENT_PAGE = 2
    # Nothing uses this yet.  Parameters will one day.
    #UNDER_PARENT_DOCSTRING = 3
```
and
```py
[UNPROCESSED, PROCESSING, PROCESSED] = range(3)
```
I think it would improve readability if we'd use `enum.Enum` from the standard library. It will also help when we add type annotations at some point in the future.

For Python 2.7 we could use the `enum34` PyPI package.

**Comment by hawkowl** [comment]
@mthuurne https://github.com/twisted/constantly does much of the same things and is already depended on by Twisted (and was actually split from Twisted), so it might be a better option

**Comment by mthuurne** [comment]
Constantly does seem to have a lot of overlap with the `enum` standard library module. However, unless it offers something extra that we need, wouldn't it be better to stick with the standard library? More people are familiar with that and more tools as well (I'm thinking of mypy in particular).

**Comment by hawkowl** [comment]
@mthuurne I don't really oppose it, but I've given up trying to use `enum` and switched to `constantly` whenever I've tried to use it in anger :( Mostly because `enum.auto()`, which we actually probably don't need.

I'm happy with whatever, though, just pointing out options :)

(My opinions on the [quality of parts the standard library](http://pyfound.blogspot.com/2019/05/amber-brown-batteries-included-but.html) is pretty low, so, factor that in :P )

**Comment by mthuurne** [comment]
I don't have a strong opinion: either `enum` or `constantly` is better than the ad-hoc solutions used at the moment. Personally I haven't run into problems using `enum`, but I do agree that parts of the standard library are rough.

Would it be an option to use `enum` for now and switch to `constantly` if we run into limitations? That kind of switch would still be easier than switching directly from the current ad-hoc enumerations to `constantly`, I think, so the effort to move to `enum` wouldn't be a waste.

**Comment by hawkowl** [comment]
@mthuurne Sure -- I don't have a problem with that. The lack of an added dependency would be nice, but I'm not sure that it's worth caring about an extra dependency on py2, tbh

**Comment by mthuurne** [comment]
We'll have to add a dependency declaration in either case, since pydoctor only indirectly pulls in `constantly` via `Twisted`.

**Comment by glyph** [comment]
I am personally in favor of `enum` because we haven't written a mypy plugin for `constantly` yet, so it works with static type checking.
