### ISSUE TITLE
Handling of undocumented variables

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#181]
When I compare the output of pydoctor's master ("new") to the published Twisted API docs ("old"), the main difference is that the new output lists undocumented variables whereas the old output did not.

The reason for this is simply that the old pydoctor didn't know or care about variables unless they were defined in a docstring using `@ivar` and similar tags. But the new pydoctor tries to gather type information from various sources and will therefore find variables even if they are undocumented.

There are quite a few undocumented module, class and instance variables in Twisted, which makes me wonder whether all of these were intended to be public and just lacking documentation, or whether some are supposed to be private but were relying on pydoctor rather than a naming convention to stay hidden.

**Comment by glyph** [comment]
Would you mind posting some examples of the output so it's easy for others to compare and weigh in?

**Comment by mthuurne** [comment]
`twisted.web.http`: [current](https://twistedmatrix.com/documents/current/api/twisted.web.http.html) vs [new](https://boxingbeetle.com/pydoctor-test/twisted.web.http.html)

There are a lot of constants that correspond to HTTP status codes. There are included in `__all__`, so they are explicitly public. But they weren't included in pydoctor's output until now.

`twisted.web.resource.Resource`: [current](https://twistedmatrix.com/documents/current/api/twisted.web.resource.Resource.html) vs [new](https://boxingbeetle.com/pydoctor-test/twisted.web.resource.Resource.html)

The `isLeaf` class variable matches an attribute on the `IResource` interface, should it should inherit that documentation, but it doesn't (in neither the current nor old situation), so that looks like a bug.

The `children` instance variable is an example of a field that I'm not sure about: since `getChild()` and `putChild()` exist, is it the intention to support users accessing the child resources directly or was this accidentally not made private? (`_children`)

`twisted.words.xish.xmlstream.XmlStream`: [current](https://twistedmatrix.com/documents/current/api/twisted.words.xish.xmlstream.XmlStream.html) vs [new](https://boxingbeetle.com/pydoctor-test/twisted.words.xish.xmlstream.XmlStream.html)

`rawDataInFn` and `rawDataOutFn` seem to be undocumented logging hooks, those should probably be documented. They are used in [an example](https://github.com/twisted/twisted/blob/trunk/docs/words/examples/xmpp_client.py).

I'm not sure about `stream`: the life cycle of this is managed by `XmlStream`, so accessing this directly would break encapsulation. Intuitively I'd say this should be a private variable, but I'm not very familiar with this part of Twisted.

I don't know why inherited instance variables have a white background instead of purple; that might be another bug.

**Comment by glyph** [comment]
> I don't know why inherited instance variables have a white background instead of purple; that might be another bug.

The DOM structure looks right, but there appears to be a very basic bug in the existing CSS selectors:

https://github.com/twisted/pydoctor/blob/c74016b8266ff0c5cea64f9c035bf0a568832f0f/pydoctor/templates/apidocs.css#L120

We just need to treat `baseclassvariable` and `classvariable` / `instancevariable` and `baseinstancevariable` the same — or at least, similarly.

**Comment by glyph** [comment]
Honestly I'm inclined to say we should probably just land this as-is, as it's an improvement to at least *see* the undocumented stuff, and then backfill the actual docs as well as potentially make more pydoctor tweaks as we go.

**Comment by mthuurne** [comment]
It has already landed in the sense that this is already in the master branch.

I fixed the CSS inconsistencies in #187.

**Comment by mthuurne** [comment]
Since the 20.3.0 docs were produced with the new variable code, I guess that makes it official, so I'll close this issue now.
