### ISSUE TITLE
Inner functions documented like methods

### ISSUE THREAD

**Issue by twm** [twisted/pydoctor#195]
The function `readBody` defines two inner functions. These are private helpers and didn't used to appear in pydoctor's output. Now they do, which is a bit confusing:

![image](https://user-images.githubusercontent.com/43662/82702851-a1c63300-9c27-11ea-9c0f-261256aff618.png)

Compare:

- [19.10.0](https://twistedmatrix.com/documents/19.10.0/api/twisted.web.client.readBody.html)
- [20.3.0 rendering](https://twistedmatrix.com/documents/20.3.0/api/twisted.web.client.readBody.html)

**Comment by mthuurne** [comment]
I agree that this is not the desired output.

What do you think would be the proper way to handle it? To omit the inner functions completely or to mark them as private, to be revealed only if the user clicks "Show Private API"?

**Comment by twm** [comment]
It's impossible for a user to call them, so I don't think that they even qualify as private API. I'd omit them completely.

**Comment by twm** [comment]
Thank you for this, @mthuurne!
