### ISSUE TITLE
Irregularities in standard library URLs

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#212]
The `stdlib_doc_link_for_name()` function in pydoctor assumes that the URL of a class or function in the standard library can be computed from its full name. However:

- the documentation for the module `xml.sax.xmlreader` is in `xml.sax.reader.html` (not `xmlreader`)
- the class `logging.FileHandler` is documented in `logging.handlers.html` (not `logging.html`)
- there are probably more cases like this

Should we hardcode such irregular mappings individually or should we use a Sphinx objects inventory for the standard library instead?

**Comment by twm** [comment]
Intersphinx, definitely.

**Comment by mthuurne** [comment]
Now that #236 is merged, this should be fixed.
