### ISSUE TITLE
interface multiple inheritance results in some missing documentation

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#22]
The documentation generated for an interface which subclasses two other interfaces seems only to include documentation for methods inherited from one of the subclassed interfaces.  For example, see http://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReadWriteDescriptor.html which includes doWrite but not doRead.

---

Imported from Launchpad using lp2gh.
- date created: 2008-12-11T22:19:00Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/307298

**Comment by mwhudson** [comment]
(by mwhudson)
That's odd.  I doubt it has anything to do with the interface-y-ness of things though.

**Comment by mwhudson** [comment]
(by mwhudson)
Oh, I see what's going on: it's because IReadWriteDescriptor doesn't define any methods of its own -- it's actually nothing to do with multiple inheritance.

**Comment by mwhudson** [comment]
(by mwhudson)
http://bazaar.launchpad.net/~mwhudson/pydoctor/dev/revision/557 contains the fix.

**Comment by mwhudson** [comment]
(by exarkun)
Is the print really part of the fix?

**Comment by mwhudson** [comment]
(by mwhudson)
Jean-Paul Calderone wrote:
> Is the print really part of the fix?
> 

Heh.  No.

**Comment by hawkowl** [comment]
This is actually a bug, see: http://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReactorThreads.html

**Comment by hawkowl** [comment]
(there's callInThread twice, but no callFromThread)

**Comment by mthuurne** [comment]
The current output for `IReactorThreads` lists both `callFromThread()` and `callInThread()` as inherited methods, once each. So I'm going to assume this issue is fixed. Please reopen if you find a case where the output is incorrect.
