### ISSUE TITLE
Exact line numbers for references in reStructedText

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#237]
Since #227, we report exact line numbers for bad cross references in epytext. However, for reStructedText I couldn't get exact line number information, since `node.line` was always `None` when `visit_title_reference()` was called for the reference node. Since there were more pressing issues to work on, I settled for reporting the starting line of the docstring instead.

I left a TODO comment in `_EpydocHTMLTranslator.visit_title_reference()` in `pydoctor/epydoc/markup/restructuredtext.py`.

**Comment by tristanlatr** [comment]
We can see in here https://stackoverflow.com/questions/58359284/docutils-get-line-number-for-nested-nodes that the line number is only set on root level elements in the tree. 

The solution would be to walk up the tree hierarchy until we find an element with a line number. It would still be best as line 0!
