### ISSUE TITLE
pydoctor assumes all docs are in the same directory

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#24]
Originally reported as Twisted issue 1886.

This has two bad effects:

it's hard for packagers to package pydoctor's output for the different bits of twisted because if (say) twisted web's docs are in /usr/share/doc/twisted-web/ they should link to twisted core's docs in /usr/share/doc/twisted-core/ and this isn't currently possible.

Similarly, the pydoctor output for nevow should link to the pydoctor output for twisted, if it knows where it is.

I think this can be addressed by loading a bunch of systems that know the base url of their documentation, and having the documentation generator look in more than just the system being generated when trying to link to something.

Having written all this out, I don't think it should be too hard...

---

Imported from Launchpad using lp2gh.
- date created: 2009-08-06T18:46:07Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/409998

**Comment by mwhudson** [comment]
(by mwhudson)
Some of this has been implemented in the multiple system stuff.  Don't really remember what the goals of the report were really...

**Comment by mthuurne** [comment]
I think you should be able to use the intersphinx support for linking to other pydoctor-generated docs. If that is insufficient or broken, please reopen and supply more details.
