### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#251]
Hello,

Last month, I've been able to review some projects that use pydoctor as a source of inspiration from here https://github.com/twisted/pydoctor/network/dependents

But now everything seems to be gone, any idea ?

Thanks

**Comment by graingert** [comment]
there's a fix for it here https://github.com/dependabot/dependabot-core/issues/2133

**Comment by adiroiban** [comment]
Thanks @graingert I think that this can be fixed as: "not something that we can do to fix it"  :) ... we can go back to old setup.py .... but I think that is better to fix dependabot instead
