### ISSUE TITLE
CSS: Better Emphasis

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#260]
I noticed the "new" pydoctor CSS: 
- Do not emphasis on element definition, it's just regular plaintext
- Do not emphasis on parameters name, it's just regular plaintext
- Do not emphasis on flags titles, i.e. "Parameters", it's just regular text

To me, this is a "layout regression" from older versions of pydoctor 

New CSS: https://twistedmatrix.com/documents/20.3.0/api/twisted.web.client.HTTPClientFactory.html

Older CSS exemples: https://twistedmatrix.com/documents/12.3.0/api/twisted.web.client.HTTPClientFactory.html or https://twistedmatrix.com/documents/12.3.0/api/twisted.web.client.html

Would be great to have the same kind of clarity.
If it's only a matter of CSS, I can try to have a look at it.

**Comment by adiroiban** [comment]
Thanks @tristanlatr for the report. For any big or small improvement that you want to see in pydoctor and for which you think you can help just go ahead and send a PR :)

We will try to review it and merge it.

Thanks again.

**Comment by tristanlatr** [comment]
@adiroiban Great. 

Also noticed that older CSS is actually more responsive that the newer, it displays better on smaller screens.

I'll see what's I can do about that.
