### ISSUE TITLE
RST support as an extra

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#264]
pydoctor relies on `docutils` to parse and format reStructedText. But other documentation formats such as epytext work fine when `docutils` is not installed. To model this in the package metadata, we can create an extra for RST support and make that extra depend on `docutils`.

**Comment by adiroiban** [comment]
I can take a look at that... this will also mean running a set of tests without sphinx and docutils installed ... `nodeps` here we come :)

**Comment by tristanlatr** [comment]
Hello,

I think rest support should be kept as a native feature.

This will impose the users to install the extra packages with

`pip install pydoctor[rst]` for instance.

This will break workflows that relies on reST. Which is much more largely used than epytext.

Plus it will make hazardous to implement #16 and #123 ( I think, I'm no expert)

**Comment by mthuurne** [comment]
Note that the pydoctor code for reST/ReST/RST (is there an official short form?) support is always included, whether you install the extra or not. The only difference is whether `pip` will install `docutils` if it wasn't already installed.

For supporting new document formats, using extras if they have external dependencies means that we can keep the dependencies of pydoctor itself low and pull in only the dependencies that the user actually needs.

The current situation is that there is no declared dependency on `docutils` at all, so declaring it in an extra is always an improvement over that.

Maybe this fine-grained dependency management is overkill though and we can make all pure Python dependencies unconditional. Are extras still widely used for optional features or only when dealing with native code that is not available everywhere?

**Comment by tristanlatr** [comment]
> The current situation is that there is no declared dependency on docutils at all, so declaring it in an extra is always an improvement over that.

Did not understand that until yesterday, I guess my builds have `docutils` already installed...

> Are extras still widely used for optional features or only when dealing with native code that is not available everywhere?

No idea, But since RST it's much more widely used, I think it should be a native feature to support it with all directives. As well as markdown, google and numpy docstrings when (or if) they will be supported.

**Comment by mthuurne** [comment]
> No idea, But since RST it's much more widely used, I think it should be a native feature to support it with all directives. As well as markdown, google and numpy docstrings when (or if) they will be supported.

I'm in favor of supporting every docstring format that sees significant use, provided that someone is willing to implement the format-specific parts (probably not me any time soon).

My concern is that when we support many formats, we'll also end up pulling in many dependencies for parsing those formats. For example in the case of Markdown, we'd need a parser library.

The question is what is worse: forcing a user to install a bunch of libraries that they don't need, or forcing them to add `[rst]` or `[markdown]` when installing pydoctor.

**Comment by adiroiban** [comment]
> The question is what is worse: forcing a user to install a bunch of libraries that they don't need, or forcing them to add `[rst]` or `[markdown]` when installing pydoctor.

+1 for using `pydoctor[rst]` extra. 

For RST I don't think that it will be a big deal.
I guess that people using RST will also using Sphinx or RST in other places so they already have docutils...so just calling `pip install pydoctor Sphinx` will do the job without the need to do `python[rst]`

**Comment by mthuurne** [comment]
The extra got added in #284.
