### ISSUE TITLE
Param types should be clickable

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#268]
Whether the type is retrieved with

```
:type arg: str
```
or from type hints
```
def get(id:str):
    pass
```

It's not clickable, even if it appears in red when figured from type hints

**Comment by mthuurne** [comment]
I was already working on hyperlinked type annotations :) But as usual, I ran into pre-existing issues (see #250) and then got pulled into other things, so it's not PR-ready yet.

For non-annotation types, we format them just like other field values. For epytext, the `type` field is just a text field, it doesn't have to contain the name of a class or built-in type. What are the semantics for reStructuredText?

Twisted uses explicit links when the type is a class or built-in type:
```
@type arg: L{str}
```

**Comment by tristanlatr** [comment]
With ReST, 
```
:type arg: str
```
The type value should be interpreted 

https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists
Says:

Container types such as lists and dictionaries can be linked automatically using the following syntax:

:type priorities: list(int)
:type priorities: list[int]
:type mapping: dict(str, int)
:type mapping: dict[str, int]
:type point: tuple(float, float)
:type point: tuple[float, float]
Multiple types in a type field will be linked automatically if separated by the word “or”:

:type an_arg: int or None
:vartype a_var: str or int
:rtype: float or str

**Comment by tristanlatr** [comment]
> The type value should be interpreted

I have this issue fixed with Google and Numpy docstring parsing, see [code](https://github.com/tristanlatr/pydoctor/blob/42fe0921cfd4dc0a0719223a5bbdf441af42bc39/pydoctor/napoleon/docstring.py#L959). but it should probably be moved to epydoc2stan and adapted to be a ParsedDocstring subclass
