### ISSUE TITLE
Safari : The sticky navbar hides the function definition focused with "#" in URL

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#270]
Here: https://mfesiem.github.io/docs/test/msiempy/msiempy.AlarmManager.html#page_size for instance, you won't actually see the definition of the `page_size` property as it's behind de navbar.

The solution would be to apply a margin somewhere but not sure where.

Also that would be good that the element focused with "#" in URL appear highlighted so we know where to look for it.

**Comment by mthuurne** [comment]
Ah yes, I've run into that problem before. I'll port over [the workaround](https://github.com/boxingbeetle/softfab/blob/965696cc0c46aa637efcc0813ebab8d5f3678b6f/src/softfab/styles/sw-factory.css#L58).

I have seen the highlighting on docs.python.org, but I don't know how they implemented it, in particular whether it is pure CSS or requires JavaScript as well.

**Comment by tristanlatr** [comment]
This is still an issue for me with Safari...

**Comment by tristanlatr** [comment]
So the issue is still present and looks like the following:

- For safari: it probably never worked, maybe the CSS trick you used simply do not work in safari. 
- For other browsers, it does work. But if the screen is narrow and the title must use multiple lines, then the margin is not enough and the top of the element is hidden.

Again, I'm unsure what's the best way to solve this issue, but it's definitely not fixed yet. The fact the the title is not fixed in height makes this a bit complicated. May be we should use JS?

**Comment by tristanlatr** [comment]
The CSS trick does not work for Safari browser. So I reopen the issue mentioning that in the title.

**Comment by tristanlatr** [comment]
The issue also occurs in Dash. 

For other browsers, if the title is long and must use multiple lines, then the margin is not enough and the top of the element is hidden. Sounds like a tough issue to solve with plain CSS no ?

I'm starting to think that the sticky navbar might not be the best idea after all. 

@mthuurne

**Comment by tristanlatr** [comment]
FYI, I've dropped the idea of having a sticky sidebar in the readthedocs theme.

**Comment by tristanlatr** [comment]
I think the best thing we could do inter of user experience is to hide the sticky sidebar by default and show it when the page scrolling up and hide it when the page is scrolling down. That requires some CSS and JS skills I think.
