### ISSUE TITLE
document that properties are not supported

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#28]
I've just spent the better part of a day figuring out why pydoctor refused to render my property in new twisted code while epydoc did so just fine, until I figured out that pydoctor doesn't know what properties are and prefers to document them like ivars (possibly read-only)

It'd be cool if the "how to use pydoctor" page mentioned this.

---

Imported from Launchpad using lp2gh.
- date created: 2009-09-07T20:54:38Z
- owner: lvh
- the launchpad url was https://bugs.launchpad.net/bugs/425939

**Comment by mwhudson** [comment]
(by mwhudson)
I'm not sure I understand, sorry.

Also sorry for taking so long to reply...

**Comment by tristanlatr** [comment]
This is probably a duplicate of #223

**Comment by mthuurne** [comment]
I think you mean #233. I prefer to actually support properties over documenting that they're not supported, so I'll close this one.
