### ISSUE TITLE
Output samples

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#285]
@adiroiban [wrote](https://github.com/twisted/pydoctor/pull/282#pullrequestreview-537405656):
> My suggestion is to create a pydoctor.test.sample.epydoc or pydoctor.samples.epydoc package in which we include all the possible usage of pydoctor with epydoc
>
> In this way, the result of this PR could be observed via
> https://pydoctor--282.org.readthedocs.build/en/282/api/pydoctor.test.html

@mthuurne [wrote](https://github.com/twisted/pydoctor/pull/282#issuecomment-732943736):
> I think it would be good to have a package that displays all the supported use cases, but I think it should be part of the documentation rather than part of pydoctor's code.
>
> One reason is that we'd want to showcase syntax that is not available in all Python versions, such as position-only parameters. Having that syntax in the main source dir could cause problems with distros that pre-optimize Python modules on install.
>
> Another reason is that I wouldn't want samples to be mixed into the indexes of the actual API docs. In the package index it would be just one line, but in the class hierarchy and name index it would produce more noise.

**Comment by adiroiban** [comment]
True. It should not be part of the pydoctor code.

We can build the sample as part if /api-demo/ or something like this... to not mix it with the actual pydoctor API.

This might need extra hacks to build it on read the docs.

------------

We don't need to demonstrate all python version. We can start with just latest python (3.9)

**Comment by mthuurne** [comment]
> This might need extra hacks to build it on read the docs.

We already have the actual API docs on readthedocs using our Sphinx extension. Perhaps we could just invoke that extension at two points in the documentation, each with a different source dir?

> We don't need to demonstrate all python version. We can start with just latest python (3.9)

There are no features in older Python versions that aren't in 3.9, nor do I expect there to be during the 3.x series. Backwards compatibility was only a concern when we supported 2.7 as well, but that is no longer the case.

The problem I was concerned about is forward compatibility: older Python versions may not be able to parse the latest language features. If the samples are in a separate source dir, this is less of a problem because only the doc builds will require a recent Python version then.

**Comment by adiroiban** [comment]
>  Perhaps we could just invoke that extension at two points in the documentation, each with a different source dir?

the current extension is not designed to allow calling pydoctor multiple times :) ... but I can see if I can hack something

**Comment by tristanlatr** [comment]
@adiroiban I did this here but I revert it cause it wasn't useful for my PR.
https://github.com/tristanlatr/pydoctor/commit/3f5d13c4ee62322af09b28b2f880c28fbc1cf2fd

**Comment by adiroiban** [comment]
I will give it a try.

My plan is to add support for calling pydoctor for an arbitrary number of times.

We need sample out for apydoc / rst / plain text :)

@tristanlatr I need your help with creating sample python packages for these 3 supported platforms. Do you think you can help ? :)

**Comment by mthuurne** [comment]
I don't think plaintext is a format we should be supporting with examples. It's useful as a fallback and for debugging, but not very practical as a main docstring format.

**Comment by adiroiban** [comment]
> I don't think plaintext is a format we should be supporting with examples. It's useful as a fallback and for debugging, but not very practical as a main docstring format.

Thanks for the info. RST and Epydoc then :)

**Comment by tristanlatr** [comment]
@adiroiban I can help you do that. But should we not link to actual projects ?

**Comment by tristanlatr** [comment]
Here are more projects using pydoctor :
    - `Wokkel <>`_
    - `Tubes <>`_
    - `pycma <https://github.com/CMA-ES/pycma>`_
    - `COCO (COmparing Continuous Optimisers)  <https://github.com/numbbo/coco>`_
    - `autokey <https://github.com/autokey/autokey>`_
    - `python-Wappalyzer <>`_
    - `msiempy <>`_

**Comment by mthuurne** [comment]
Finding an uncommon feature being used in a large project can be difficult. In the case of Twisted I often use `grep` on the source to figure out which module contains the feature, since just browsing the output is too inefficient.

Linking to real projects is useful too, but more as a showcase for people wondering whether they want to start using pydoctor and less for people already using it wondering how to document a particular part of their project.

**Comment by adiroiban** [comment]
I am looking for condensed showcase content that will go here https://github.com/twisted/pydoctor/pull/314/files#diff-ed01f83f0dd7a2f4bb998bd5fb88e11215fd1395b54744cb3ccb6979935b23d9

The content should cover all features and should make sure that we don't demonstrate the same feature too many times.

**Comment by tristanlatr** [comment]
> We need sample out for apydoc / rst / plain text :)

The best to handle this issue and not have to call pydoctor many times (it's harder to manager: more files and more args) would be ether to:

- implement #16 
- or autodetect the docformat and used the appropriate parser on a per-docstring basis
- and/or, as @mthuurne mentionned have a sphinx extension to output like pydoctor does inside the user manual it self. 

But anyway, it could be useful for the users to call pydoctor many times, so #314 is great

**Comment by mthuurne** [comment]
I think implementing #16 is useful in any case, as it helps projects that have integrated code from other projects, or projects that want to transition from one doc format to another. It might even be useful for a project to use a simple syntax (epytext or even Markdown in the future) for most docstrings and use RST for parts of the documentation where that simple syntax is insufficient.

Autodetection is something I'd rather avoid, since it's hard to do well, especially if the number of supported doc formats grows in the future.

A Sphinx extension that skips the front-end (`driver.py`) should be possible in theory, but I don't know how many practical issues it would run into.

**Comment by adiroiban** [comment]
> Autodetection is something I'd rather avoid, since it's hard to do well, especially if the number of supported doc formats grows in the future.

+1


> A Sphinx extension that skips the front-end (`driver.py`) should be possible in theory, but I don't know how many practical issues it would run into.

If we have a complete view model that contains all the doc related info, it should not' be a problem to create a SphinxHTMLWriter.

The problem is that the current HTML Writer is not only a writer/rendered ,but it also triggers  the generation of view model data.
