### ISSUE TITLE
Do not print Unknown Field: when there is an unknown field

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#288]
The expected behaviour, would be, as Sphinx, to just print the field name in bold.
Maybe apply `.title()`.

**Comment by mthuurne** [comment]
In general I prefer tools to complain loudly when non-existing syntax is used, as that helps discover errors early.

There is the `newfield` mechanism that can be used to define new fields that pydoctor doesn't know out-of-the-box. It's used in epydoc like this:
```rst
:newfield contributor: Contributor, Contributors (Alphabetical Order)
:contributor: `Glyph Lefkowitz  <mailto:glyph@twistedmatrix.com>`__
:contributor: `Edward Loper  <mailto:edloper@gradient.cis.upenn.edu>`__
```

**Comment by tristanlatr** [comment]
Replaced by #456
