### ISSUE TITLE
Release 2020.12.0 tracking

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#290]
While there is only one week left in 2020.11, I want to try and get a pydoctor release out soon, so let's stick to that as a target version number for now.

Things that need to be done:
- parameter annotations: #136, #217, #229 and #283
- #255, since this includes a deprecation
- #233?
- #153?
- check whether deprecations are documented correctly
- update release notes
- automatically release on tag push (we had this ability in Travis, but Travis itself became unworkable)

While there are 4 issues related to parameter annotations, it's not as much work as it may seem:
- #136 doesn't require a PR, only the closing of other tickets
- #229 could be implemented for parameter fields only for now
- #283 could be limited to what we need to support pos-only and kw-only params, without major changes in presentation
- I already have a local branch for #217, but it was stranded several times as other issues had to be resolved first (like #283)

~~I have some doubt about whether deprecations are documented correctly, since there is Twisted-specific code for documenting deprecations in `pydoctor.templatewriter.pages.functionchild` that isn't executed when generating Twisted's API docs. It's possible this is obsolete code, but it could also mean that some deprecations are currently omitted from the output.~~ Also Twisted now supports [parameter deprecations](https://twistedmatrix.com/trac/ticket/9844) and I haven't seen any code that handles documentation generation for that.
 
I'd like to hear opinions on other tickets that really need to go into the next release, or tickets that are listed here but aren't crucial. Also help on resolving the to-do items is welcome of course.

**Comment by mthuurne** [comment]
I was looking at the wrong coverage report (for the unit tests); when generating Twisted's API docs the deprecation code is executed.

**Comment by adiroiban** [comment]
A lot of tickets here.... I think that this will be 2020.12.0 ... or maybe even 2021

**Comment by mthuurne** [comment]
Some tickets take multiple days, while others can be solved in an hour. For the ones with question marks, I want to give them a go, but if complications turn up, we can postpone them.

The parameter annotations is the item I really wanted in this release and that item is almost finished.

**Comment by adiroiban** [comment]
ok. ping me on IRC if you need any help. I can help with the reviews...but I don't have the motivation and time  to work on new feature

**Comment by mthuurne** [comment]
Here is a draft for the release notes:

- Python 3.6 or higher is required
- There is now a user manual which can be built with Sphinx or read online on Read The Docs; this is a work in progress and the online version will be updated between releases
- Added support for Python language features:
  * Type annotations of function parameters and return value are used when the docstring does not document a type
  * Coroutine functions (`async def`) are included in the output
  * Keyword-only and position-only parameters are included in the output
- Output improvements:
  * Styling changes to make the generated documentation easier to read and navigate
  * The pydoctor version is included in the "generated by" line in the footer
- New option `-W`/`--warnings-as-errors` to fail your build on documentation errors
- Linking to the standard library documentation is more accurate now, but does require the use of an intersphinx inventory (`--intersphinx=https://docs.python.org/3/objects.inv`)
- Improved error reporting:
  * More accurate source locations (file + line number) in error messages
  * Warnings were added for common mistakes when documenting parameters
  * Clearer error message when a link target is not found
- Reliability:
  * Fix crash when analyzing `from package import *`
  * Fix crash when the line number for a docstring error is unknown
  * Better unit test coverage, more system tests, started adding type annotations to the code
  * Unit tests are also run on Windows

**Comment by adiroiban** [comment]
The release notes look good. Much appreciated!

-------

> Should the Sphinx extensions also be mentioned or are they not ready yet for end users?

One extension is private.... the other  is public and ready for end users. I plan to use it on twisted/twisted.

----------

For the release notes, since pydoctor doesn't have too many parallel or long lived PRs, maybe we can update the release notes together with each PR, but direct edit of a NEWS.rst or ReleaseNotes.rst file. Without using towncrier or other tools.

**Comment by mthuurne** [comment]
> One extension is private.... the other is public and ready for end users. I plan to use it on twisted/twisted.

Does this describe the extension well?

- Added a [Sphinx extension](https://pydoctor.readthedocs.io/en/latest/usage.html#building-pydoctor-together-with-sphinx-html-build) for embedding pydoctor's output in a project's Sphinx documentation

> For the release notes, since pydoctor doesn't have too many parallel or long lived PRs, maybe we can update the release notes together with each PR, but direct edit of a NEWS.rst or ReleaseNotes.rst file. Without using towncrier or other tools.

Right now pydoctor doesn't have a lot of parallel PRs, since you have been reviewing them very quickly. Many thanks for that! But there were times in the past when there were between 5 and 10 PRs awaiting review.

That said, we can be optimistic and assume that PR review is going to stay quick in the future. Also not every PR needs an entry in the release notes, since some don't change user-visible properties and some address unreleased regressions. So I think it's fine to have a "next release" section in the release notes and add to that in PRs.

**Comment by mthuurne** [comment]
I think it's better to not try and rush the release out in a few hours, just to be able to stick to the version number. I do still want to release some time this week.

These things are now done:
- parameter annotations
- automatically release on tag push
- writing release notes

Still to do:
- #255, since this includes a deprecation
- #233?
- #153?
- check whether deprecations are documented correctly
- #284: this includes the `rst` extra and documentation updates
- [create all parents of output dir](https://github.com/twisted/pydoctor/pull/284/files#r530283343)
- convert release notes to RST and commit

**Comment by mthuurne** [comment]
#302 would be good to solve as well, since it limits the usefulness of the new `--warnings-as-errors` option.

**Comment by mthuurne** [comment]
Almost there!

Done:
- deprecate `--add-package` and `--add-module` options (issue #255, PR #309)
- button to show/hide private API on index pages (issue #153, PR #311)
- docs update, `rst` extra, create all parents of output dir (PR #284)
- only fail the build on warnings that are caused by bad source code (issue #302, PR #306)
- enable intersphinx cache by default (#307)

Still to do:
- support for `@property` decorators (issue #233, PR #312 ready for review)
- improve the way the deprecation message is interleaved with progress reporting when not using `--quiet`
- check whether deprecations are documented correctly
- convert release notes to RST and commit

**Comment by mthuurne** [comment]
Deprecation mechanisms that Twisted uses:
- `@deprecated` on a function/method: works
- `@deprecated` on a class: does not occur in the source at the moment
- `@deprecatedProperty`: deprecation notice missing
- `deprecatedModuleAttribute`: deprecation notice missing
- `@deprecatedKeywordParameter`: does not occur in the source at the moment

**Comment by mthuurne** [comment]
Fixing `@deprecatedProperty` requires merging #316 and the following patch to be added to Twisted:
```diff
diff --git a/src/twisted/python/_pydoctor.py b/src/twisted/python/_pydoctor.py
index 30d8683770..2a92b2ba69 100644
--- a/src/twisted/python/_pydoctor.py
+++ b/src/twisted/python/_pydoctor.py
@@ -83,7 +83,9 @@ def getDeprecated(self, decorators):
         if isinstance(a, ast.Call):
             fn = astbuilder.node2fullname(a.func, self)
 
-            if fn == "twisted.python.deprecate.deprecated":
+            if fn in (
+                    "twisted.python.deprecate.deprecated",
+                    "twisted.python.deprecate.deprecatedProperty"):
                 try:
                     self._deprecated_info = deprecatedToUsefulText(self, self.name, a)
                 except AttributeError:
```

**Comment by mthuurne** [comment]
I opened #317 as a reminder about `@deprecatedKeywordParameter`. Since there are no uses of `@deprecatedKeywordParameter` in Twisted at the moment, fixing it does not have priority.

I also opened #319 about `deprecatedModuleAttribute`. There are about 40 uses of `deprecatedModuleAttribute` in Twisted, so fixing it would improve the usefulness of the generated documentation. However, looking at the many different usage patterns for this mechanism (read the issue for a list), I don't think this is something we should be attempting to solve before the release. Note that this is not a regression: there have never been deprecation notices generated for `deprecatedModuleAttribute`.

**Comment by mthuurne** [comment]
Done:
- support for `@property` decorators (issue #233, PR #312)
- check whether deprecations are documented correctly:
  - `@deprecated` works
  - `@deprecatedProperty` doesn't work, PR #316 fixes this
  - `@deprecatedModuleAttribute` doesn't work, won't be fixed in this release (#319)
  - `@deprecatedKeywordParameter`: doesn't work, but is unused (#317)

To do:
- improve the way the deprecation message is interleaved with progress reporting when not using `--quiet` (PR #320, ready for review)
- support for custom property decorators (PR #316, ready for review)
- convert release notes to RST and commit

I assume that PR #314 doesn't need to go into this release, is that correct?

**Comment by adiroiban** [comment]
> I assume that PR #314 doesn't need to go into this release, is that correct?

That is correct. @mthuurne  as long as you agree with the general interface of the Read The Docs integration PR #314 of using a List or a Dict for the same configuration value.

I am going to reduce the scope of that PR and send it for review soon.

**Comment by mthuurne** [comment]
The release is now available on PyPI. :)
