### ISSUE TITLE
Support customization of all html templates

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#3]
Originally reported as Twisted issue 3125:

> Pydoctor has a directory full of templates it uses to generate html output. It would be nice if these templates could be customized somehow (other than directly editing them).

---

Imported from Launchpad using lp2gh.
- date created: 2009-08-06T18:51:47Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/410008

**Comment by mwhudson** [comment]
(by mwhudson)
Comments from trac:

2008-04-11 08:16:52+00:00 changed by mwh ¶

I agree with the goal, but it's pretty vague. Can you explain specific need you had that led to you opening this ticket?

2008-04-11 13:17:35+00:00 changed by exarkun ¶

Specifically, I want to include the visitor-tracking javascript that is used on the main twisted site in the generated api docs. This basically amounts to a static script tag somewhere near the end of the page.

**Comment by mwhudson** [comment]
(by mwhudson)
I still don't really have any good ideas for how to address this.  Two options that spring to mind, neither very satisfactory:

1. Allow configuration of the directory from which templates are read.  This would allow any possible customization, but it's basically encouraging copy/paste/hack, and would make upgrading pydoctor trying, I suspect.

2. Allow a few carefully chosen hooks that allow inserting content at various places in the template.

Hm, after writing this, this lumbers in from the massive over-engineering department:

3. Involve XSLT somewhere.

JP, any thoughts?

**Comment by mwhudson** [comment]
(by exarkun)
The way we tried to allow customization in Mantissa is to split up template files into somewhat smallish pieces (deciding on what "small" meant on an arbitrary, subjective, case-by-case basis) and then allowed each template to be overridden separately.  This reduces copy/paste/hack somewhat, although we still ended up with some instances of it.

This might just mean option 1 from above, plus a fallback for anything that's missing, and then being liberal about slicing up existing templates when it would be helpful for someone trying to customize output.

For my particular use case, I currently have modifications to common.html, index.html, nameIndex.html, problemObjects.html, and summary.html, adding the same footer to each.  So, a separate footer template that I could override to include something at the end of every page pydoctor emits would satisfy this particular case.

**Comment by mwhudson** [comment]
(by mwhudson)
That makes sense.

**Comment by tristanlatr** [comment]
This would be soooooooo nice. 

I think copy/paste/hack for small files would be manageable, with a notice to freeze pydoctor version if users are using custom templates.

Currently the way to customize templates is to apply a patch to the `pydoctor.templatewriter.util.templatefile` function, as Twisted do.
https://github.com/twisted/twisted/blob/trunk/src/twisted/python/_release.py

**Comment by tristanlatr** [comment]
We could create 3 new files (empty by default): `header.html` (before everything), `title.html` (just after the main header) and `footer.html` in the `templates` folder. 
With that, a `--template-dir` option that would allow to overwrite the templates, saying that only templates files `header.html`, `footer.html` and `title.html` should be overwritten. 

The title.html file is for the Twisted use cas where the "Go to the latest version of this document." is after the main header.

**Comment by tristanlatr** [comment]
This feature has been implemented in https://github.com/twisted/pydoctor/pull/299. 

[Read the docs](https://pydoctor.readthedocs.io/en/latest/customize.html#include-custom-html)

This mean that Twisted Ticket [#4693](https://twistedmatrix.com/trac/ticket/4693) can be closed in no time by using the new templating system and adding `header.html` and `extra.css`. There is already [this example](https://pydoctor.readthedocs.io/en/latest/custom_template_demo/pydoctor.html) 

Twisted patching the `templatefile` method is ignored by the new templating system. See the PR for more details.
