### ISSUE TITLE
"from .module import foo" style imports not supported

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#30]
Running "pydoctor foo" on the following structure gives "foo.quux:0 invalid ref to baz" and does not link "baz" in the generated HTML page for "foo.quux".

foo/**init**.py
1:# blank

foo/bar/**init**.py
1:from .other import baz

foo/bar/other.py
1:def baz():
2:    pass

foo/quux.py
1:"L{baz}"
2:from .bar import baz

---

Imported from Launchpad using lp2gh.
- date created: 2010-11-18T01:52:29Z
- owner: mwhudson
- the launchpad url was https://bugs.launchpad.net/bugs/676784

**Comment by mthuurne** [comment]
This was implemented in #199.
