### ISSUE TITLE
Enable intersphinx cache by default?

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#300]
We support caching intersphinx inventories, but this requires passing the `--enable-intersphinx-cache` option on the command line. I think it would make more sense to enable the cache by default and provide an option to disable it.

The default cache duration is only one day, so I don't think there is a big risk of working with stale data if we enable caching by default.

**Comment by adiroiban** [comment]
I am fine with enabling caching by default.

I see that in the original PR #143 this was approved right away without a discussion.

I see that commit message talks about 1 week of cache , but the implementation was 1 day from the start.
So if you think that it make sense, we can also update the default cache time.

**Comment by mthuurne** [comment]
I'm not sure changing the default will have much of an impact; Read the Docs seems to be serving files with an expiry time one hour into the future.
