### ISSUE TITLE
Fix flaky generation of object inventory for multiple projects.

### ISSUE THREAD

**Issue by adiroiban** [twisted/pydoctor#339]
It looks like when the pydoctor sphinx extension is used for multiple projects, the object inventory is generated with some errors.

The generation always works on local dev computers but it fails 50% to 30% of the time on GitHub Actions.

For now, the workaround is to call the main project generate last... but we need to see what is going on here.

**Comment by mthuurne** [comment]
You wrote on IRC that the likely cause is that the same URL is used in the mapping for the inventory of the real project and the demo project. Looking at the implementation of the `intersphinx` extension, it uses the URL as the key in the inventories cache, so that supports this theory.

**Comment by adiroiban** [comment]
I will try to find a fix for that :) ... I wanted to keep simple and this is why I have not added support for multiple API builds for the Read The Docs inventory build... but I will add support for that.

**Comment by mthuurne** [comment]
I describe an idea for a possible fix [here](https://github.com/twisted/pydoctor/pull/332#discussion_r549274750).

**Comment by mthuurne** [comment]
@adiroiban fixed this in #340.
