### ISSUE TITLE
Add necessary blank lines to pydoctor.napoleon generated reStructuredText to separate field lists from adjacent paragraphs

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#366]
Example of docstring that gets incorrectly parsed:
```
"""
Returns something. 
Returns
-------
list
"""
```

After `str(NumpyDocstring(docstring))` :

```
"""
Returns something. 
:rtype: `list`
"""
```

Renders like

<img width="386" alt="by default 2021-02-20 at 11 59 34 PM" src="https://user-images.githubusercontent.com/19967168/108616033-b19dbe00-73d7-11eb-8d9a-54b7939fd7b3.png">

Workaround: Add required blank lines before fields sections. 
```
"""
Returns something. 

Returns
-------
list
"""
```

**Comment by twm** [comment]
That parsing appears correct to me. reST [field lists](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#field-lists) must be separated from adjacent paragraphs by a blank line. Sphinx will give the same result.

It sounds like the reStructuredText generated by `pydoctor.napoleon` is incorrect.

**Comment by tristanlatr** [comment]
Thanks for this insight. 

I'll try to see what I can do to ensure this white lines are getting automatically added. 

But it seems weird, the napoleon tests are passing and I did not add extra white lines anywhere to make it pass.

**Comment by tristanlatr** [comment]
If someone have correct implementation for a method as follow, I would be glad to integrate it. 

```
def _ensure_blank_line_before_fields(self, lines: List[str]) ->  List[str]:
"""
Add necessary blank lines to the reST formatted docstring in order to separate field lists from adjacent paragraphs. 
"""
```

This regex can probably help: `re.compile(r'^:(\S+)(?:\s(\S+?))?:((?:\n?(?: .*|$))+)')`. 

Any help would be appreciated :)
