### ISSUE TITLE
Representation of constants values

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#377]
Having the value of the constant defined here and there would be very useful.

Epydoc had a great thing: the `epydoc.markup.pyval_repr. PyvalColorizer`, and it happens that some people already made the code work with Python3: https://github.com/nltk/epydoc/blob/master/src/epydoc/test/py3/pyval_repr.doctest

What we need to figure is how to know when displaying the value? I'm unsure of how Epydoc did this. `typing.Final` is an idea, whether the variable name is upper cased is another clue to indicate that the variable is final. Or we could just always try to render the value. How difficult is it to construct initial the value from AST when it's a single assignment ? It should not be complicated, or at least we should not handle that complexity!

Related: https://github.com/twisted/pydoctor/issues/364#issuecomment-803660886

**Comment by mthuurne** [comment]
> What we need to figure is how to know when displaying the value? I'm unsure of how Epydoc did this. `typing.Final` is an idea, whether the variable name is upper cased is another clue to indicate that the variable is final. Or we could just always try to render the value.

I think we should only display values for constants, not variables that might change their value at runtime.

> How difficult is it to construct initial the value from AST when it's a single assignment ? It should not be complicated, or at least we should not handle that complexity!

Let's say we have these definitions:
```py
SPECIES_PIG = 1 << 11
SPECIES_FROG = 1 << 10

COLOR_RED = 1 << 2
COLOR_GREEN = 1 << 1
COLOR_BLUE = 1 << 0

KERMIT_LIKE = SPECIES_FROG | COLOR_GREEN
"""It's not easy."""
```

We could use `ast.literal_eval()` to convert the AST to a Python value. In the example above, that would result in `KERMIT_LIKE = 1026`, which is not very informative.

We could use the `astor` library to get a string representation of the AST value. This would be simple to implement, but it would limit our ability to colorize and link the output. In the example above, `astor` would produce `KERMIT_LIKE = SPECIES_FROG | COLOR_GREEN` as flat text.

Probably the best user experience would be if we'd implement a custom presenter as an AST visitor, similar to `pydoctor.epydoc2stan._AnnotationFormatter`. We could then hyperlink `SPECIES_FROG` and `COLOR_GREEN` to their respective documentation locations. And other formatting ideas could be taken from the `PyvalColorizer` that you mentioned.

There is some overlap with showing the default values for parameters. For example, there is #294, which I don't think needs to be solved at the same time as this issue, but it would be useful to consider sharing code between the constant presentation and the default value presentation.

---

Does a definition like `FOO = BAR` define a constant, an alias or both? Currently aliases are not Documentables, but they probably should be, see #313. But in that case, do we have to decide whether `FOO` is more of an alias or a constant, or could it be both simultaneously?

**Comment by tristanlatr** [comment]
I'm currently porting Epydoc's `PyvalColorizer` to modern python3 (not using `six`). Then I was going to simply use `ast.literal_eval()`. And perhaps go further and try to recover `re.compile` expressions from AST, since the colorizer has a great support for those. 

But the auto-linking of such constructed constants could be a nice feature too. 

Once I've finished with that, AST support could be added to `PyvalColorizer`, it would use the `_AnnotationFormatter` under the hood (that we would need to move to a different module to avoid circular import, and be extended a little bit to understand constructs with `ast.Name` in it -  for your use case). But I'm really not sure of how complex such an exercise is, honestly. 

Regarding aliases, yes, they could easily be Attributes with a special kind I think.

> Does a definition like FOO = BAR define a constant, an alias or both?

I would say alias. but `BAR` is a constant, so `FOO` is an alias to a constant.

**Comment by tristanlatr** [comment]
> There is some overlap with showing the default values for parameters.

I would go even further, I think of merging those 3 objects together `_AnnotationFormatter`, `_ValueFormatter` and `PyvalColorizer`. Sounds sane right ?

**Comment by tristanlatr** [comment]
Cheering myself for this awesome feature!

Coming soon!

<img width="315" alt="by default 2021-06-10 at 9 01 46 PM" src="https://user-images.githubusercontent.com/19967168/121615510-12a4dc80-ca2f-11eb-888b-3dbd55a8232e.png">
