### ISSUE TITLE
ReadTheDocs theme

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#391]
Hi, I'm working on a readthedocs theme for pydoctor.

Should I open a PR once it's finished ? Or should I create a new repository to host the theme ?

<img width="807" alt="by default 2021-05-07 at 9 34 45 AM" src="https://user-images.githubusercontent.com/19967168/117457685-76f7ec00-af17-11eb-8069-dfb53d0a5666.png">

Thanks,

**Comment by adiroiban** [comment]
Just WOW :) That would be awesome.  Thanks!

I guess that a RTD theme hosted inside pydoctor could help to server as a reference for template customization.

I agree that hosting any random theme inside pydoctor is no feasible ... but I think that RTD is an exception.

We also have custom RTD extension for sphinx hosted inside pydoctor.

**Comment by tristanlatr** [comment]
Happy that you find this awesome. 

This theme will really be nice when we have the #370 (Sidebar) merged :) But before, we need your review on #360 ;)

**Comment by mthuurne** [comment]
I think it's worth offering this to our users. Integrating it into the `pydoctor` repo might not be the best way though, since users typically don't clone the repo or download a source tarball. Maybe we can create a new repo under the Twisted organization on GitHub, to give it an official status but make it easier to install via GitHub's release system or archive links.

**Comment by adiroiban** [comment]
Maybe the theme can be distribute  with the pydoctor wheel package ... and have a special config file `--template-path=ReadTheDocs`  . pydoctor can look for some special values , and not handle them as full path, but instead replace them with a path located inside the  pydoctor installation wheel

**Comment by tristanlatr** [comment]
> and have a special config file --template-path=ReadTheDocs . pydoctor can look for some special values , and not handle them as full path

This looks very complicated for only this special case. If we are going this route, I think we should package the theme inside a python package instead.

But I think just a folder is much more simple for now.

I'll create a repo then,.

**Comment by tristanlatr** [comment]
Here for now: https://github.com/tristanlatr/pydoctor-theme-readthedocs

**Comment by tristanlatr** [comment]
@adiroiban @mthuurne Feedback welcome: https://tristanlatr.github.io/pydoctor-theme-readthedocs/index.html

**Comment by tristanlatr** [comment]
I agree that it would be good to be able to use the `readthedocs` theme without having to download it.
`mkdocs` has a few theme already packaged with the program, we should do the same I think.

We could add a synonym to the `--template-dir` option like, `--theme` for instance, and make it check if the name matches a known theme before to consider the string as a path. 

@mthuurne What so you think ?
