### ISSUE TITLE
an interface's attributes should be included in an implementations documentation

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#40]
If an interface defines attributes and an implementation does not provide its own documentation, the interface's documentation should be included in the implementations page.

---

Imported from Launchpad using lp2gh.
- date created: 2012-03-20T23:18:45Z
- owner: mwhudson
- the launchpad url was https://bugs.launchpad.net/bugs/960708

**Comment by mthuurne** [comment]
Inheritance of interface attributes was implemented in e7ea447a.
