### ISSUE TITLE
Link Labels

### ISSUE THREAD

**Issue by devlog42** [twisted/pydoctor#404]
Hello everybody,

First of all I want to say that I am enthusiastic about pydoctor and there is already a small project whose API I generated with it: https://devlog42.github.io/qtgrid/

What I'm about now isn't really a big deal. I'm only trying to put a label on a link in a docstring. I found the following documentation on this: https://pydoctor.readthedocs.io/en/stable/docformat/restructuredtext.html#cross-references

For example, if I have a reference like this:
\`project.package1.package2.module.MyClass\`

How can I give it a label so that only *MyClass* appears?
I use pydoctor[rst] in version 21.2.2

Thanks in advance
devlog42

**Comment by tristanlatr** [comment]
Hi @devlog42 ,

You can do the following in reStructuredText : 

```
`project.package1.package2.module.MyClass <MyClass>`
```

Hope this helps!

**Comment by devlog42** [comment]
Thanks for the tip - but no, that wasn't the solution either. ;-)

But luckily I came up with it myself in the meantime. Together with https://www.writethedocs.org/guide/writing/reStructuredText/ and a bit of trial and error, it works as follows:

    `MyClass <project.package1.package2.module.MyClass>`

Thanx, and happy coding

**Comment by tristanlatr** [comment]
@devlog42 

Must be the fatigue! This is waht I meant...

Happy coding!

**Comment by devlog42** [comment]
@tristanlatr 

LOL, you're welcome!

BTW: What's the difference between tired and exhausted?

When you run in front of a car, you get tired
When you run behind a car, you get exhausted.
