### ISSUE TITLE
Getting organize for next release 

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#420]
Hi, 

With the new templating system in place, it's probably time to do a release. 

But before, I think the following PRs should be merged:

- #419 because it's a really easy fix for a real problem
- #389 because it introduces improvements to the templating system, this way we can already use the [pydoctor-theme-readthedocs](https://github.com/tristanlatr/pydoctor-theme-readthedocs) as a custom template. 

Other PR can probably wait until another release. 

Tell what you think,

Thanks

**Comment by tristanlatr** [comment]
I think we should make a release now. I’ll create a branch 21.9.x and tag it.

Do I need any approval for such process ?

Thanks.

**Comment by adiroiban** [comment]
looks like we have a few release docs here https://github.com/twisted/pydoctor/blob/master/docs/source/contrib.rst#releasing-and-publishing-a-new-package

It contains "First commit the version update to master and wait for tests to pass."

I would prefer to have a separate branch on which the version is updated on on which we check the tests are green.

Once the tests are green, create a tag/release based on the code from the branch.

if all is ok, the version of the branch can be updated to `.dev0` and the branch can be merged in master.

But yes @tristanlatr  feel free to create the release branch. I can review it.

Thanks!

**Comment by adiroiban** [comment]
the release is triggered from here https://github.com/twisted/pydoctor/blob/master/.github/workflows/unit.yaml#L83

any time a tag is created

**Comment by tristanlatr** [comment]
Hi @adiroiban ,

So if I understand correctly, first I create a release branch, then I update the version number to « 21.9.0 », then I merge this branch to master ( with your approval ), then I tag this version with the tag « 21.9.0 », this will trigger the release process on pypi.

I do not understand why you want a dev0 version, though ?

**Comment by adiroiban** [comment]
yes. That is what is documented right now.

But I will suggest using this process:

* create a branch: name it release-21.9.0
* On the branch update the version and release notes and release date
* Create a PR for that branch and get an approval
* Create a tag based on the HEAD of the release branch
* This will trigger the release
* Update the code on the branch and have version 21.9.0.post0 (or dev0)
* Merge the branch

In this way, version 21.9.0 only existed for a brief period of time...and the main branch will have 21.9.0.

Right now, you will check the code and it says  version 21.2.2, but the code from master is not 21.2.2

https://github.com/twisted/pydoctor/blob/master/setup.cfg#L3

**Comment by adiroiban** [comment]
And if someone tries to do a pip install from the git source, they will get a .post0 or .dev0  development version and not the public/final release 21.2.2

**Comment by tristanlatr** [comment]
Ok I get it. Perfect. I’ll do that later today.

**Comment by tristanlatr** [comment]
Release 21.9.0 done ! 🥳🥳
