### ISSUE TITLE
Run tests with python `PYTHONWARNINGS=error`

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#438]
No warnings should be triggered while running the tests. This would avoid issues like #435.

There is still currently one `UserWarning` being triggered: 

```
driver.py:473: UserWarning: Writer 'InMemoryWriter' does not support HTML template customization with --template-dir.
```

We should first change the tests such that this warning get triggered inside a `pytest.warns` clause such that it does not get listed in the warnings summary and we assert it triggers correctly. 

Then, we can enable errors on warnings, see [PYTHONWARNINGS docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS).

**Comment by graingert** [comment]
ah this project uses pytest https://github.com/twisted/pydoctor/blob/master/setup.cfg#L74

so it should be a bit easier than I expected originally:

```cfg
[tool:pytest]
testpaths = pydoctor/test
python_files = test_*.py
addopts = --doctest-glob='*.doctest' --strict-config --strict-markers
doctest_optionflags = ELLIPSIS IGNORE_EXCEPTION_DETAIL
xfail_strict = true
filterwarnings = error
```
