### ISSUE TITLE
documentation describes sphinx-autodoc as "hazardous" but I don't know what that means

### ISSUE THREAD

**Issue by glyph** [twisted/pydoctor#443]
Is that attempting to describe some security risk in the way sphinx configuration works? Is it just an aesthetic judgement of its style?

**Comment by tristanlatr** [comment]
Not a security risk, this has to do with the fact that there are directives for every entry, like `autoclass`, `automodule`, etc. And a lot of options. Making the learning curve more hard than a CLI tool like pydoctor.

I agree this is a bit of a design judgment and I would be inclined to remove it or replace it with something else.

**Comment by tristanlatr** [comment]
@glyph  Can you think of a better wording ?

**Comment by glyph** [comment]
I think maybe just including a sentence or two instead of the word. Perhaps "more complex"?
