### ISSUE TITLE
port to the ast module

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#45]
pydoctor should really use the now-standard ast module, not the old, crufy & deprecated compiler package.

No idea how much work this is.

---

Imported from Launchpad using lp2gh.
- date created: 2012-03-25T21:32:35Z
- owner: mwhudson
- the launchpad url was https://bugs.launchpad.net/bugs/964804

**Comment by mthuurne** [comment]
This was done in #151.
