### ISSUE TITLE
--docformat: invalid choice: 'numpy'

### ISSUE THREAD

**Issue by icecore2** [twisted/pydoctor#453]
When trying to change the docformat, it throws an error:
```
(venv) C:\project>pydoctor --docformat=numpy --make-html --html-output=Docs\ project
Usage: pydoctor [options] SOURCEPATH...

pydoctor: error: option --docformat: invalid choice: 'numpy' (choose from 'epytext', 'plaintext', 'restructuredtext')```

**Comment by adiroiban** [comment]
Hi,

What version of pydoctor do you use?

 I don't think the numpy format is supported in the public release.
As you see in the error messages only epytext / plaintext and rst format are supported.

Numpy was added here https://github.com/twisted/pydoctor/pull/358 but not yet released.

If would help if you could try the development version and report any issues with numpy.

Thanks!

**Comment by tristanlatr** [comment]
@icecore2 you can install the latest development version of pydoctor with:

`pip install git+https://github.com/twisted/pydoctor`

The numpy docstring format should then be available. I just want #402 merged and I’ll publish a new version after that.
