### ISSUE TITLE
Command line option to show all private objects

### ISSUE THREAD

**Issue by iosonofabio** [twisted/pydoctor#461]
Related to #50, #327, et al.

One solution to all those problems, if not perfect, would be to have a command-line option (which works also via the sphinx ext) to get rid of the "show/hide private" business and just show everything in the docs, private or otherwise.

Of course, folks might want to have a more granular control, but for many situations this might be a good enough compromise: it's better to show users a little too much than to miss key API objects...

Happy to make a PR if you think it's useful

**Comment by tristanlatr** [comment]
Hi, @iosonofabio,

Would you like the private objects to keep their gray color - and order ? If yes, the right way of doing this is through a custom theme (what you are already doing in python-igraph). This will also be the way if you'de like to get rid of the "show/hide private" business. 

If you'de like private members to be considered public, we need new code. 
See for example of how to customize the `System` class: https://github.com/twisted/pydoctor/issues/388#issuecomment-827900981

See this discussion about adding new options/fields to control object privacy: https://github.com/twisted/pydoctor/issues/36 . This is a ticket that I want to see closed for a long time!

I think we're ready for adding one new option, something like: `--make-public=igraph._igraph` that would be repeatable and taking either the full name of an API object or a fnmatch pattern (which could be "*").

If you are interested into making a PR to add this new option, that would be greatly appreciated! 

We discussed (in issue #36) the option to add a docstring field, it would a bit harder on te implementation side, though. Also, there is another way of working around this: names re-exported by the `__all__` variables are public names in Python. To make the submodule `_igraph` public, just re-rexport it in `igraph` package in the `__all__` variable. We do not currently support that. An issue with that approach (that should be supported anyway) is that all public names must be added to the `__all__` variable unless python will not import your names when doing a wildcard import. 

The command line option seems like a good start to me, what do you say ?

**Comment by iosonofabio** [comment]
Thanks for the quick reply. We're using `__all__` in `python-igraph` at the moment, but I'm thinking more of a catchall situation, where people have no time/resources for making a proper theme, etc.

Yes something like `--make-public` with `action='append'` would work, with perhaps a special `--make-public='*'` value that makes everything public. I'll try and find the time for a PR in the next days, thank you!

**Comment by tristanlatr** [comment]
Thanks @iosonofabio,

The custom theme is really just:

```css
body.private-hidden .private {
    display: inherit!important;
}
```

It would be nice that this new feature can replace the twisted customization for handling their privacy, see https://github.com/twisted/pydoctor/issues/36#issuecomment-802800071 So I think we need `fnmatch`, also we need `--make-public` and `--make-private` with a priority to `--make-public` when a name is matching two expressions (if a name is the exact value, then give to priotity to that privacy).

Such that we can handle cases like twisted's with `--make-public=twisted.test` `--make-private=twisted.test.*`, 
`--make-public=twisted.test.proto_helpers`.

Tell me what you think,

**Comment by iosonofabio** [comment]
@ntamas @szhorvat see the last comment for CSS suggestions on making everything public, in case you would like to use it

@tristanlatr sounds good... the more generic the less likely the PR will actually see the light of day, so let me see how much time I can carve out for this without overpromising. Will keep you posted.

**Comment by tristanlatr** [comment]
> @ntamas @szhorvat see the last comment for CSS suggestions on making everything public, in case you would like to use it

I think this is kind of what you guys are already doing. 

Talk to you later

**Comment by tristanlatr** [comment]
Fix in latest version with new argument --privacy, see docs https://pydoctor.readthedocs.io/en/latest/customize.html#override-objects-privacy-show-hide
