### ISSUE TITLE
Collapsing modules with many submodules in the Module Index

### ISSUE THREAD

**Issue by not-my-profile** [twisted/pydoctor#465]
Some Python modules have hundreds of submodules (e.g. `pygments.lexers` or `searx.engines`). If all of these are displayed on the Module Index the index becomes hard to use ... whatever comes alphabetically after the module containing the many submodules is only reachable after much scrolling and it's unnecessarily difficult to get an overview of the overall module structure (which I'd argue is the main purpose of the Module Index).

So I think it would be a good idea to automatically omit submodules from the Module Index for modules that contain more than a specific amount of modules (maybe 50 by default?). If deemed necessary that amount could be made configurable. Ideally the Module Index would still indicate something like "(200 submodules)" to not give the wrong impression that the module is empty.

What do you think about this?

**Comment by tristanlatr** [comment]
Hi, @not-my-profile,

Thanks for the proposal.

I think we should still display the modules names, but maybe omit the documentation summary (only if they are more than a certain number and we're talking about modules, not packages). I agree a `<details>` tag that would expand the list of modules listed inline would be the best in terms of screen space and comprehension of the package architecture.

The code that takes care of the module summary generation is there: https://github.com/twisted/pydoctor/blob/master/pydoctor/templatewriter/summary.py#L20-L39

In terms of implementation I think it wouldn't be very hard.

**Comment by not-my-profile** [comment]
Hi. Ah yes omitting the documentation summaries is a great solution, I didn't think of!

In that case I however don't think a `<details>` tag is necessary, or am I missing something?

**Comment by tristanlatr** [comment]
Could work without too, yes.
