### ISSUE TITLE
Ugly line wrapping of API member names

### ISSUE THREAD

**Issue by not-my-profile** [twisted/pydoctor#466]
```python
class Foo:
    def some_methods_have_longer_names(self):
        pass
```

results in the following:

![image](https://user-images.githubusercontent.com/73739153/151960783-65432c6f-b731-4ff0-8f77-f36657c6ac48.png)

because of the following CSS:

https://github.com/twisted/pydoctor/blob/996e03a6042c386e2aa00c248e746f8cc506b81c/pydoctor/themes/base/apidocs.css#L247-L249

I think `word-break: break-word;` should be removed ... breaking words in the middle looks horrible.

**Comment by tristanlatr** [comment]
Hi @not-my-profile,

Yes it's not the best. I agree. 

Do you have some CSS talents? I think we could use some.

The issue with the word break is that if it's not sed to `break-word`, the name can overlap with it's documentation summary. Do you know a way we could adjust the documentation table cell's padding not to overlap when these is a long name? Or another workaround for this issue?

Thanks
