### ISSUE TITLE
--introspect-c-modules loads foreign extension modules

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#48]
If I build Twisted's extension modules using PyPy and then run pydoctor using CPython, passing the --introspect-c-modules flag, pydoctor fails with this exception:

Traceback (most recent call last):
  File "/home/exarkun/Projects/pydoctor/trunk/bin/pydoctor", line 12, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/exarkun/Projects/pydoctor/trunk/pydoctor/driver.py", line 318, in main
    system.addPackage(path, prependedpackage)
  File "/home/exarkun/Projects/pydoctor/trunk/pydoctor/model.py", line 618, in addPackage
    self.addPackage(fullname, package)
  File "/home/exarkun/Projects/pydoctor/trunk/pydoctor/model.py", line 620, in addPackage
    self.addModuleFromPath(package, fullname)
  File "/home/exarkun/Projects/pydoctor/trunk/pydoctor/model.py", line 637, in addModuleFromPath
    (suffix, mode, type))
ImportError: /home/exarkun/Projects/Twisted/trunk/twisted/runner/portmap.pypy-14.so: undefined symbol: _Py_InitPyPyModule

It seems the logic for deciding whether a .so should be loaded as an extension or not needs a little more smarts.

---

Imported from Launchpad using lp2gh.
- date created: 2012-05-09T18:57:16Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/997272

**Comment by mwhudson** [comment]
(by mwhudson)
Do you think just catching ImportError is enough?  Clearly extension modules _can_ raise any error which loaded (the can also call abort() I guess).

**Comment by mwhudson** [comment]
(by exarkun)
Perhaps?  It seems this particular case could be solved by recognizing the newer naming convention for extension modules and not loading extensions that the current Python runtime wouldn't load (perhaps with a warning?).

Actually, the misbehavior is a little worse.  My tree actually has _both_ CPython _and_ PyPy builds of these extension modules.  pydoctor should pick up the CPython version when running on CPython and ignore the PyPy version.

    exarkun@top:~/Projects/Twisted/trunk$ find -name '*.so'
    ./twisted/runner/portmap.pypy-14.so
    ./twisted/runner/portmap.so
    ./twisted/test/raiser.so
    ./twisted/python/_initgroups.so
    ./twisted/python/_initgroups.pypy-14.so
    ./twisted/python/sendmsg.pypy-14.so
    ./twisted/python/sendmsg.so
    ./twisted/internet/_sigchld.pypy-14.so
    ./twisted/internet/_sigchld.so
    exarkun@top:~/Projects/Twisted/trunk$

**Comment by mthuurne** [comment]
The only shared object I see in my Twisted tree when using CPython is `src/twisted/test/raiser.cpython-38-x86_64-linux-gnu.so`, so it seems CPython is now using more detailed file names as well. Can this issue still occur under supported versions of Python? (Python 3.6+, CPython and PyPy)

The [module loading](https://github.com/twisted/pydoctor/blob/7457030a45d94bce0678331ee6b758fc7aa8f467/pydoctor/model.py#L832) for introspection was rewritten as part of the Python 3 port, so that might also affect this issue.

@exarkun: Pinging you since you submitted the original ticket in Launchpad.

**Comment by exarkun** [comment]
I don't really recall any details about this issue, sorry.

**Comment by mthuurne** [comment]
I'll close it then. If anyone runs into this problem again with a recent pydoctor, they can re-open this issue.

Thanks for the quick reply.
