### ISSUE TITLE
Stop separating packages and modules on package pages

### ISSUE THREAD

**Issue by not-my-profile** [twisted/pydoctor#480]
Pydoctor currently shows packages before modules:

![image](https://user-images.githubusercontent.com/73739153/152670035-e31cdbdc-1528-4062-af6d-6926a5f39964.png)

I find this really irritating. As an API user I don't really care about the distinction between packages and modules, I just want to find the module/package I need quickly and for that it would help if modules/packages were listed together alphabetically.

Within a package subpackages and submodules share the same namespace so I think displaying them together makes the most sense. For example `sphinx` and `sphinx_ext` shouldn't be 9 rows apart they should be next to each other.

What do you think about this? If we display them intermixed they should of course both have the same background color.

**Comment by tristanlatr** [comment]
I like having the distinction between modules and packages on the first overview. I don’t know if the intermixed order should be enabled with an option or by default, I’de rather not introduce a new option for that. I’m not sure what’s the best way forward.

But I think we should still keep 2 different colors. Also it’s so easy to customize the css with a template, so I’de like to keep it like this for the CSS.

**Comment by not-my-profile** [comment]
I'm curious why do you like that distinction on the first overview?

**Comment by tristanlatr** [comment]
As developper, it’s useful to have this since it gives a information about the structure of the project. But maybe the intermixed view with the kind indication on the left would be sufficient too.

**Comment by adiroiban** [comment]
I am +1 for having everything order alphabetically.
You can have the module and package info on each separate row.
