### ISSUE TITLE
There's a random chance that the superclass isn't linked

### ISSUE THREAD

**Issue by not-my-profile** [twisted/pydoctor#482]
To reproduce this we need a package with three files:

`example/__init__.py`

```python
from . import bar
```

`example/foo.py`

```python
from . import xxx

class Foo(object):
	pass
```

`example/bar.py`

```python
from . import foo

class Bar(foo.Foo):
    pass
```

Running `pydoctor example` has a random chance that it fails to link the superclass:

| correct | bugged |
|--|--|
|![image](https://user-images.githubusercontent.com/73739153/152678490-fe010e3a-59cf-4720-8161-e052e07ded62.png)|![image](https://user-images.githubusercontent.com/73739153/152678473-e26f32e8-089e-4b6f-87e6-f15fdbaa93bc.png)

The bug is difficult to debug since it doesn't always occur, running pydoctor with `PYTHONHASHSEED=0` or `PYTHONHASHSEED=1` does however seem to help with reproducing.

The underlying issue is that how pydoctor [currently handles cyclic imports is not reproducible](https://github.com/twisted/pydoctor/issues/138#issuecomment-730394192).

**Comment by tristanlatr** [comment]
Probably linked to #429 and #412. 

Know that I’m working on a new ast builder that should solve a lot of our problems. See #430

**Comment by tristanlatr** [comment]
Note that solving the processing order does not solve the import cycles handling. 

What would solve this issue is a major refactoring if the builder. Thing that I’m doing with [pydocspec](https://github.com/tristanlatr/pydocspec)
