### ISSUE TITLE
not all epytext errors detected by documentation builder

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#51]
pydoctor has two formats it uses to report epytext problems.  One, we catch, "name: error text".  Another we don't:

```
these 3 objects' docstrings are not proper epytext:
    twisted.mail.imap4.getBodyStructure
    twisted.mail.imap4._SinglepartMessageStructure._extended
    twisted.mail.imap4._MultipartMessageStructure._extended
```

The result is that errors of this type don't turn the documentation builder red, which is bad.

---

Imported from Launchpad using lp2gh.
- date created: 2013-02-23T07:11:35Z
- owner: tom.prince
- the launchpad url was https://bugs.launchpad.net/bugs/1027879

**Comment by mwhudson** [comment]
(by tom.prince)
This is tricky to handle, since pydoctor doesn't appear to have a consistent error format.

I think the sane solution to this to get pydoctor to output errors in a standard format, and then
we don't need to figure out what all to expect.

Michael: I'd be happy to do this, if it would be acceptable.

**Comment by mwhudson** [comment]
(by mwhudson)
i'm fairly sure that the errors reported at the end are a summary of errors reported during the run.  if that's not the case, then that's a bug.

i'm also totally open to making pydoctor's error reporting more consistent...

**Comment by mthuurne** [comment]
I think this is fixed now: docstring errors are reported when they occur, in addition to being listed in the summary.

Is the summary useful? A plain log might be simpler to work with. Also, I'm going to assume that projects will strive to have no errors most of the time, so the list of errors shouldn't be so long that a summary is really needed.

#112 suggests using a proper logging system, which would also help in making the error reporting more consistent.
