### ISSUE TITLE
SOURCEPATH (positional arguments) in project config files

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [twisted/pydoctor#563]
I am aware that you write in the docs: _Currently, positional arguments cannot be configured with a file._

I couldn't find an Issue about that. Isn't there a future goal to improve that behavior?

I am quite new to pydoctor but from my point of view the config files are nearly useless if I also have to use the commandline with them. I'm using config files because I don't wan't to use command line anymore. I just want to type `pydocotor` in the projects root and `pydoctor` should figure out what to do by itself reading a config file.

Does `pydoctor` use the current working directory as `SOURCEPATH` by default? Maybe this is not a problem for people using a more traditional project folder layout. But I am using the `src`-layout. I have to do `pydoctor ./src/packagename` in my case.

**Comment by tristanlatr** [comment]
No, pydoctor does not use the current directory as the default source path.

But, there is a way to define source path from the confit file.

Related to issue #537

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Sorry I don't see how #527 can help me with my problem. Can you be more specific please.

**Comment by tristanlatr** [comment]
Sorry I’ve linked the wrong number :/ here: #537 @Codeberg-AsGithubAlternative-buhtz

**Comment by tristanlatr** [comment]
Basically,  one can use in `setup.cfg`: 

```
[tool:pydoctor]
add-package =
    src/mylib
```

Or with `pyproject.toml`

```
[tool.pydoctor]
add-package = ["src/mylib"] 
```

But this will currently trigger a deprecation warning, which can be ignored until be have a final decision regarding #537

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I see. Then the documentation should be improved about this.
It doesn't matter that this option is currently official "deprecated". It just works so it must be documented.
And you can also put the Issue link into the documentation and a comment about the possible future.
