### ISSUE TITLE
DOC: --process-fields does not exist

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [twisted/pydoctor#568]
The documentation [here](https://github.com/twisted/pydoctor/blob/master/docs/source/codedoc.rst#type-fields) tells me about the commandline argument `--process-fields`. But looking into `--help` tells me it does not exist.

But there is a `--process-types`.

It does something but I am not sure if it is a synonym for `--process-fields`. I expected type names as hyperlinks. But they don't.

**Comment by tristanlatr** [comment]
It’s a typo the option your looking for is `—process-types`. I’ll fix it.


Please share a example of the links that are not well processed please.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Does this interfere with the `--intersphinx` option? I don't know if I need `--intersphinx` or `--process-types` or both.

**Comment by tristanlatr** [comment]
No it’s unrelated.
But if the intersphinx is not registered, you might not be able to link to some object, because their location is unknown.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Mhm.... You mean `--intersphinx` has no effect when `--process-types` is not set? In that case the latter should be mentioned also in the doc section about intersphinx.

**Comment by tristanlatr** [comment]
> Mhm.... You mean --intersphinx has no effect when --process-types is not set?

Absolutely not. Please read the help of the cli args.
