### ISSUE TITLE
DOC: Remove Sphinx references from headlines and topics

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [twisted/pydoctor#569]
I would strongly recommand to remove/rename "sphinx" from any heading and toc entry.

e.g. https://pydoctor.readthedocs.io/en/latest/sphinx-integration.html

The topic should be named _Linking from pydoctor to external API docs_. That is how a human would call it and how a human word search for it.

Even if you have experience with Sphinx you may not know how its linkage to external API docs works and what object inventories are. In the current situation readers (and searchers) are misdirected and can not find what they are looking for.

I am not in the details of Sphinx. But in my understanding pydoctor doesn't use Sphinx but some of its "standards" (e.g. napoleon and object inventories). So don't talk about "Sphinx" but about the standard and what it does.
In that case I am also not sure if the arguments name `--intersphinx` is the correct term. I had no idea what this is for and why my pydoctor should interact with Sphinx. I'm using pydoctor because I never want to touch Sphinx again and waste my live time with it. ;)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I would also add informations about how to search and find `object.inv` files from external API docs.
I am not totally new to Python but it is the first time I learned about that concept. I don't know how to look for such files.

e.g. I am looking for `pandas` `object.inv`. But it is not here `https://pandas.pydata.org/pandas-docs/stable/object.inv`.

**Comment by tristanlatr** [comment]
Intersphinx is a Sphinx concept, and whether we like it or not, it’s called intersphinx. 

Pydoctor can integrate with Sphinx, but can also be used standalone. 

I’m going to close this issue since the references to Sphinx are ok. We integrate with it at the end of the day, so normal that our down talk about it.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I assume my point wasn't clear enough.

You should not delete the Sphinx references but the Spinx references in the headlines.
Don't name the technique (Sphinx) but the task (link to external API doc) because a new user will always search for a task because she/he doesn't know the technique. If she/he would know the technique she/he wouldn't search.

**Comment by adiroiban** [comment]
I guess that this can be clarified by sending a PR with the suggested changes :)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I think it is not a good idea to ask for code contribution from someone who doesn't know what is going on and who is not well experienced with the project.
I was just offering my new-user-perspective.

**Comment by tristanlatr** [comment]
> I think it is not a good idea to ask for code contribution

we’re talking about documentation here. Thanks btw for your contributions on the documentation. 

You’re more than welcome to change the wording of the documentation to be more clear.
