### ISSUE TITLE
twisted.python.deprecate: Recognize calls to twisted.python.versions.Version as well

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#610]
```
twisted-22.4.0/src/twisted/conch/ssh/common.py:81: Invalid call to twisted.python.deprecate.deprecated(), first argument should be a call to incremental.Version()
```

https://github.com/twisted/twisted/blob/ed86633aa46970d6c9c2c1389ceae296fb6114d8/src/twisted/conch/ssh/common.py#L17

It should be fixed by understanding that `twisted.python.versions.Version` is an alias to `incremental.Version`:

https://github.com/twisted/twisted/blob/ed86633aa46970d6c9c2c1389ceae296fb6114d8/src/twisted/python/versions.py#L1

**Comment by adiroiban** [comment]
I would prefer to have this solved by using a simple string in Twisted, without the need for `incremental` or other complex data structures.

The deprecations message should only show a text.
It should not care about version numbering, version comparison... etc.

I am happy to remove the usage of `incremental` in Twisted from the deprecation messages as long as I have a reviewing buddy :)

**Comment by adiroiban** [comment]
My goal was to simplify twisted.python.deprecate :)

But if supporting incremetal is easy, no problem.

--------

In an ideal world, there would be a de-facto deprecation library used by all Python projects ... and pydoctor only has to support it.

I am aware of https://github.com/Julian/regret but I don't think it is widely adopted.
