### ISSUE TITLE
Use tuple instead of lists to store the Class._mro attribute

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#638]
Once the MRO is computed it should never be changed, so using immutable objects is best.

**Comment by exarkun** [comment]
It's not widely accepted that a tuple is just "an immutable list".  It very common to consider a tuple a heterogeneous container whereas a list is a homogeneous container.

If you are just looking for "an immutable list", consider using a list with a `collections.abc.Sequence` annotation.

**Comment by exarkun** [comment]
It's easy to have a workflow where they are "enforced".  Just require the type checker not emit errors.  It's easy to set up CI to do that.

This is as "enforced" as it gets.  Even if you switch to using a tuple, nothing stops someone from writing code that replaces it with a list and then mutates it.

**Comment by exarkun** [comment]
> Tuples offers faster iteration speed, this will be my last argument.

Cool.  I wasn't aware of this.  Do you have any numbers showing how much faster switching from list to tuple in these places makes pydoctor in real life (eg, how much of a speedup do we get when building Twisted's docs)?

Is it faster only on CPython or is it also faster on the fast Python runtime, PyPy?

**Comment by exarkun** [comment]
> I'll be happy to only use `Sequence` annotations and roll back to using lists, if that's how I can get your approval on PR https://github.com/twisted/pydoctor/pull/706 ;)

Without other compelling reasons to keep the tuple switch, that's what I'd recommend.  Thanks.
