### ISSUE TITLE
some invalid epytext markup is not reported as such

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#7]
If a function's docstring includes epytext markup documenting a parameter which the function does not have, pydoctor doesn't seem to consider this an error.  It generates output which includes the documentation for the parameter without emitting a warning or error.

eg

  exarkun@charm:~$ mkdir foo
  exarkun@charm:~$ touch foo/**init**.py
  exarkun@charm:~$ cat > foo/foo.py
  def bar(baz):
          """
          @param quux: foo
          """
  exarkun@charm:~$ pydoctor --make-html --add-package foo/
  adding directory /home/exarkun/foo
  2/2 modules processed 0 warnings  
  WARNING: guessing foo for project name
  writing html to apidocs using pydoctor.nevowhtml.writer.NevowWriter
  starting ModuleIndexPage ... took 0.038186s
  starting ClassIndexPage ... took 0.002309s
  starting IndexPage ... took 0.007698s
  starting NameIndexPage ... took 0.007809s
  starting UndocumentedSummaryPage ... took 0.003291s
  3/3 pages written 
  exarkun@charm:~$

---

Imported from Launchpad using lp2gh.
- date created: 2008-10-23T15:11:37Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/288181

**Comment by mwhudson** [comment]
(by mwhudson)
This is a bit related to #960709 I guess.

**Comment by mthuurne** [comment]
This got fixed in #296.
