### ISSUE TITLE
Generate NoneType link without additional type information

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#70]
Currently, in order to generate a link to the Python documentation for NoneType additional type information must be provided: 
L{NoneType <types.NoneType>}.  Since this is so common, it would be better if Pydoctor were able to resolve L{NoneType} without the additional type information.

---

Imported from Launchpad using lp2gh.
- date created: 2013-11-19T15:10:54Z
- owner: staceysern
- the launchpad url was https://bugs.launchpad.net/bugs/1252762

**Comment by mthuurne** [comment]
`types.NoneType` is gone in Python 3. See discussion in #76 for details.
