### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#733]
It’s time to drop support for python 3.6. The next version will be last one to support python 3.6.

Once it’s done, we’ll need to enabled PEP 563 on every modules. Potentially doing a script that checks that all our files starts with the future import.

**Comment by buhtz** [comment]
Why not dropping 3.7, too? It is not supported by Python itself anymore.

In face of resource of a FOSS project I would vote to also drop 3.8, because it will lose official security fix support next year.
