### ISSUE TITLE
invalid ref to NoneType

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#76]
L{NoneType} issues an error: invalid ref to NoneType.

NoneType is a built-in type, so it should be valid.

---

Imported from Launchpad using lp2gh.
- date created: 2014-04-16T20:19:33Z
- owner: wsanchez
- the launchpad url was https://bugs.launchpad.net/bugs/1308747

**Comment by mthuurne** [comment]
`NoneType` is weird: `type(None)` presents itself as `<class 'NoneType'>`, but the name `NoneType` itself is undefined.

In Twisted, `L{None}` is used instead, while epydoc uses `C{None}`. PEP 484 states "When used in a type hint, the expression `None` is considered equivalent to `type(None)`."

So in my opinion, there is no need to support `L{NoneType}` and that construct could even be argued to be incorrect. In any case, there is no separate entry for `NoneType` in the Python API docs: we'd have to link to `None` instead, which is another argument to just write `L{None}`.

**Comment by mthuurne** [comment]
Ah, I see now that Python 2 did have `types.NoneType`, but this no longer exists in Python 3. Since we're dropping Python 2 support in the next major release, I think it's safe to close this then.
