### ISSUE TITLE
Codecov is failing

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#782]
Here is the log:
```
     Gzipping contents..
    Compressed contents to 27567 bytes
    Pinging Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    Direct to s3 failed. Using backup v2 endpoint.
    Uploading to Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: 404 Client Error: Not Found for url: https://codecov.io/upload/v2?commit=932c13df34b50e48ffddee9587d6ac09382c1a19&branch=780-transform-deprecated-typing-annotations&pr=781&build_url=http%3A%2F%2Fgithub.com%2Ftwisted%2Fpydoctor%2Factions%2Fruns%2F8768226898&service=github-actions&build=8768226898&slug=twisted%2Fpydoctor&yaml=.codecov.yml&package=py2.1.13
Tip: See all example repositories: https://github.com/codecov?query=example
```

@adiroiban any idea ? I'm not sure who set up codecov. Not me.

**Comment by adiroiban** [comment]
Hi

I will take a look. Codecov S3 server was failing a bit more often recently...not sure if this is the reason.

We can also implement coverage reporting via GitHub Actions only... similar to what we have for twisted/towncrier

**Comment by adiroiban** [comment]
I just re-run a job from the main branch and codecov publish was succesful

https://github.com/twisted/pydoctor/actions/runs/8756510054/job/24062635255#step:8:45


codecov coverate is still pushed using the old python upload tools, that is now deprecated....

but it still works

https://github.com/twisted/pydoctor/blob/master/tox.ini#L41-L48

One thing that we can do on error, is to automatically wait 30 seconds and retry the upload

**Comment by adiroiban** [comment]
From what I can see, codecov was setup here , oct 2020 , by Maarten 
https://github.com/twisted/pydoctor/commit/82ad7d63f01387950a2a38609a39cbb5a0bc88c3

**Comment by adiroiban** [comment]
One thing that we can do for cleanup for GitHub Actions, is update to nodejs 20

We have all these warnings

![image](https://github.com/twisted/pydoctor/assets/204609/f259f6c9-6b59-4aaf-b35f-b0f5021a52a2)


and at some point, things will break.

For now, there are still many people using the old nodejs16 actions, and GitHub has decided to keep support for now... but support can be removed anytime

**Comment by adiroiban** [comment]
OK. I see the problem. It's alwasy best to also send a link to the build.


https://github.com/twisted/pydoctor/actions/runs/8768226898/job/24063009027#step:8:58

The important but is that the codecov was failing, but tox was ending the job with a success.

This needs to be fixed

I will give it a try to update to use the new codecov action


```
.query commit=932c13df34b50e48ffddee9587d6ac09382c1a19&branch=780-transform-deprecated-typing-annotations&pr=781&build_url=http%3A%2F%2Fgithub.com%2Ftwisted%2Fpydoctor%2Factions%2Fruns%2F8768226898&service=github-actions&build=8768226898&slug=twisted%2Fpydoctor&yaml=.codecov.yml&package=py2.1.13
    Gzipping contents..
    Compressed contents to 27135 bytes
    Pinging Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    Direct to s3 failed. Using backup v2 endpoint.
    Uploading to Codecov...
    Retrying 1/5 in 2s..
    Retrying 2/5 in 2s..
    Retrying 3/5 in 2s..
    Retrying 4/5 in 2s..
    Retrying 5/5 in 2s..
    {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: 404 Client Error: Not Found for url: https://codecov.io/upload/v2?commit=932c13df34b50e48ffddee9587d6ac09382c1a19&branch=780-transform-deprecated-typing-annotations&pr=781&build_url=http%3A%2F%2Fgithub.com%2Ftwisted%2Fpydoctor%2Factions%2Fruns%2F8768226898&service=github-actions&build=8768226898&slug=twisted%2Fpydoctor&yaml=.codecov.yml&package=py2.1.13
Tip: See all example repositories: https://github.com/codecov?query=example
  codecov: OK (34.43=setup[9.94]+cmd[1.[42](https://github.com/twisted/pydoctor/actions/runs/8768226898/job/24063009027#step:8:43),23.06] seconds)
  congratulations :) (34.50 seconds)
```
