### ISSUE TITLE
Output markdown

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#80]
It would be useful to have pydoctor generate markdown, which can be served by the readthedocs mkdocs 

http://www.mkdocs.org/
http://mkdocs.readthedocs.org/en/latest/

---

Imported from Launchpad using lp2gh.
- date created: 2014-11-19T04:19:13Z
- owner: jayvdb
- the launchpad url was https://bugs.launchpad.net/bugs/1394070

**Comment by mwhudson** [comment]
(by mwhudson)
That's an interesting idea.  Sadly I don't know when I'll get to it...

**Comment by mthuurne** [comment]
We have a Sphinx extension now, for integrating pydoctor's output in a larger documentation set. And Read the Docs supports Sphinx these days. So is there still a use case for outputting Markdown?

**Comment by tristanlatr** [comment]
I think there are some advantages to actually use mkdocs or Sphinx build system to build API documentation from files generated by PyDoctor: RST or MD.

This offers :
- Searchable API builtin with mkdocs or sphinx search boxes
- More unified integration with mkdocs or sphinx (the TOC always aside + same style)
- Flexibility: Markdown can be rendered the way the people want

**Comment by mthuurne** [comment]
RST is well-defined and pretty expressive, so I can see that working out. But Markdown cannot even handle tables without extensions and those extensions work differently for each processor, so I fear it would become a mess.

How is mkdocs search implemented these days? The last time I checked (a little under 2 years ago) it just dumped all documentation content into a JSON file, which doesn't scale well for large projects such as Twisted.

**Comment by tristanlatr** [comment]
> Markdown cannot even handle tables without extensions

We could display the summary tables as simple lists. 

But yeah RST it also a good way to go. We should make sure the output logic is well decoupled into the templatewriter module.

So we can start writing other template writer classes that can plug into PyDoctor with the 
`--html-writer=HTMLWRITER` argument, which should be renamed `--writer-class` or something no? I must say I don't really understand the use case of changing the writer class if it's not to write to another format.

**Comment by adiroiban** [comment]
I think that this can be closed as won't fix.

It would be nice to keep this use case in consideration when working on custom templates / json ouput.

In theory, you can create a custom pydoctor end user presentation theme / template  that will ouput the result in Sphinx friendly RST (with toc and all) ... and this can later be passed to sphinx.

**Comment by tristanlatr** [comment]
Yep I can do that, but should we not link to actual project that uses pydoctor instead?
With an indication which format they use.

**Comment by mthuurne** [comment]
OK, let's close this one in favor of Sphinx integration and JSON export.
