### ISSUE TITLE
Process the docstrings summary from docutils nodesm not source

### ISSUE THREAD

**Issue by glyph** [twisted/pydoctor#86]
compare https://twisted.github.io/tubes/docs/tubes.fan.html and https://twisted.github.io/tubes/docs/tubes.fan.In.html

**Comment by mwhudson** [comment]
Oh yeah, I bet the summary string is seen as just "A fan.In presents a single fount that delivers the inputs from multiple drains::"

I guess just s/::$/:/ on the summary would fix this, seems a touch gross though.

**Comment by glyph** [comment]
It sounds like the "right" answer would be to extract the summary post-parsing – you're making it sound like it's extracted as source text?

**Comment by mwhudson** [comment]
Ah yes, that would definitely make more sense (currently it is indeed done on the source).

**Comment by tristanlatr** [comment]
When PR #386 is merged, we can start working on generating the summary HTML from the `docutils` document and fix this this issue.

**Comment by tristanlatr** [comment]
So ``pydoctor``, two years ago, was processing the summary from the docutils node, at least in the case of the reStructuredText: https://github.com/twisted/pydoctor/commit/253f9a90b8dd9ad629e60d0f7ca88e043a1aff75#diff-9b0b2f7d4a8b784bf04769b8343cf25857cdead8111fda83f61fea1f121a6b90L258 . 

It would not be too hard to bring back this to life, and add tests to it.
