### ISSUE TITLE
new stylesheet doesn't seem to hide private stuff

### ISSUE THREAD

**Issue by glyph** [twisted/pydoctor#87]
https://twisted.github.io/tubes/docs/classIndex.html shows all private names looking equivalent to public ones.

**Comment by mwhudson** [comment]
Did this change with @hawkowl's recent stuff?

**Comment by glyph** [comment]
I think so yes.

**Comment by hawkowl** [comment]
Yeah, this is actually a different thing that what I implemented, mine was on the class itself, not the class index.

**Comment by mthuurne** [comment]
This got fixed in #311.
