### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by ikalev** [twisted/pydoctor#91]
I have started fixing the code to make it source-compatible with Python 3 and the changes I had to make were very trivial. However, ``twisted.web.template`` is a dependency. It seems that this module has been recently ported by @hawkowl :

  https://github.com/twisted/twisted/commit/eee2adfc145db321eb0c53d2a68171799ec8c3ee

Is there anything else blocking Python 3 support?

**Comment by mwhudson** [comment]
Well, python3 lacks the compiler package so astbuilder needs to be rewritten/ported to ast.  That's a good idea anyway (should help performance, for one thing) but not a trivial thing.

**Comment by ikalev** [comment]
Oh, I see, thanks. There seems to be another issue as well - epydoc is a dependency, so it won't be trivial indeed. But I might start working on it at some point because I really like Pydoctor.
