### ISSUE TITLE
very odd interpreter path after installing in my cpython trunk virtualenv

### ISSUE THREAD

**Issue by rbtcollins** [twisted/pydoctor#95]
I have a virtual env of cpython trunk. That thinks the world is 3.6 (its not, and there's no python3.6 in existance on my machine). I installed pydoctor there and trying to run it was hilarious:

testtools-cpython-trusty-64) robertc@trusty-64:~/personal/testtools$ pydoctor
-bash: /home/robertc/.virtualenvs/testtools-cpython-trusty-64/bin/pydoctor: /usr/local/bin/python3.6: bad interpreter: No such file or directory

To reproduce, build cpython trunk. Make a virtualenv (./python -m venv ~/somepath)
activate the venv and install recent tools and then pydoctor

```
. ~/somepath/bin/activate
pip install -U pip
pip install -U wheel setuptools
pip install pydoctor
pip list

alabaster (0.7.6)
Babel (1.3)
docutils (0.12)
epydoc (3.0.1)
extras (0.0.3)
fixtures (1.3.1)
ghp-import (0.4.1)
Jinja2 (2.7.3)
linecache2 (1.0.0)
MarkupSafe (0.23)
pbr (1.2.0)
pip (7.1.0)
Pygments (2.0.2)
python-mimeparse (0.1.4)
pytz (2015.4)
setuptools (18.0.1)
six (1.9.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.8)
testtools (1.8.1.dev6, /home/robertc/personal/testtools)
traceback2 (1.4.0)
Twisted (15.2.1)
unittest2 (1.1.0)
wheel (0.24.0)
zope.interface (4.1.2)

```

**Comment by mthuurne** [comment]
Is this issue still relevant?

I haven't had any issues running pydoctor in a venv, with Python 3.6, 3.7 and 3.8, so it's possible the problem was fixed at some point in the last 5 years.

**Comment by mthuurne** [comment]
I'm closing this now. If a similar problem pops up again, please let us know.
